from typing import Any, Self
from abc import ABC, abstractmethod

from grammers.client import Client
from grammers.tl import enums
from grammers.custom import User

class EventKind:
    class Logined:
        def __str__(self) -> str: ...

    class Error:
        def __str__(self) -> str: ...

    class RawUpdate:
        def __str__(self) -> str: ...

class EventBuilder:
    class Logined:
        def __new__(cls, filter: Any | None) -> Self: ...
        def __str__(self) -> str: ...

    class Error:
        def __new__(cls, filter: Any | None) -> Self: ...
        def __str__(self) -> str: ...

    class RawUpdate:
        def __new__(cls, filter: Any | None) -> Self: ...
        def __str__(self) -> str: ...

Logined = EventBuilder.Logined
Error = EventBuilder.Error
RawUpdate = EventBuilder.RawUpdate

class EventCommon(ABC):
    def __new__(cls, client: Client) -> Self: ...
    @property
    @abstractmethod
    def kind(self) -> EventKind: ...
    @property
    def client(self) -> Client: ...
    def to_dict(self) -> dict: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class LoginedEvent(EventCommon):
    def __new__(cls, client: Client, user: User) -> Self: ...
    @property
    def kind(self) -> EventKind: ...
    @property
    def user(self) -> User: ...

class ErrorEvent(EventCommon):
    def __new__(cls, client: Client, error: BaseException) -> Self: ...
    @property
    def kind(self) -> EventKind: ...
    @property
    def error(self) -> BaseException: ...

class RawUpdateEvent(EventCommon):
    def __new__(cls, client: Client, update: enums.Update) -> Self: ...
    @property
    def kind(self) -> EventKind: ...
    @property
    def update(self) -> enums.Update: ...
