from typing import Any, Optional

class TLObject:
    @staticmethod
    def pretty_format(
        obj: Any, indent: Optional[int] = 0
    ) -> str: ...
    def __repr__(self, slf: TLObject) -> str: ...
    def __eq__(self, other: Any) -> bool: ...
    def to_json(self) -> str: ...
    def to_bytes(self) -> list[int]: ...
    def to_dict(self) -> dict: ...

class TLRequest:
    @staticmethod
    def pretty_format(
        obj: Any, indent: Optional[int] = 0
    ) -> str: ...
    def to_dict(self) -> dict: ...
