"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

AccessPointRule = types.AccessPointRule

AccountDaysTtl = types.AccountDaysTtl

AiComposeTone = types.AiComposeTone | types.AiComposeToneDefault

AiComposeToneExample = types.AiComposeToneExample

AttachMenuBot = types.AttachMenuBot

AttachMenuBotIcon = types.AttachMenuBotIcon

AttachMenuBotIconColor = types.AttachMenuBotIconColor

AttachMenuBots = types.AttachMenuBotsNotModified | types.AttachMenuBots

AttachMenuBotsBot = types.AttachMenuBotsBot

AttachMenuPeerType = (
    types.AttachMenuPeerTypeSameBotPm
    | types.AttachMenuPeerTypeBotPm
    | types.AttachMenuPeerTypePm
    | types.AttachMenuPeerTypeChat
    | types.AttachMenuPeerTypeBroadcast
)

AuctionBidLevel = types.AuctionBidLevel

Authorization = types.Authorization

AutoDownloadSettings = types.AutoDownloadSettings

AutoSaveException = types.AutoSaveException

AutoSaveSettings = types.AutoSaveSettings

AvailableEffect = types.AvailableEffect

AvailableReaction = types.AvailableReaction

BadMsgNotification = types.BadMsgNotification | types.BadServerSalt

BankCardOpenUrl = types.BankCardOpenUrl

BaseTheme = (
    types.BaseThemeClassic
    | types.BaseThemeDay
    | types.BaseThemeNight
    | types.BaseThemeTinted
    | types.BaseThemeArctic
)

BindAuthKeyInner = types.BindAuthKeyInner

Birthday = types.Birthday

Boost = types.Boost

BotApp = types.BotAppNotModified | types.BotApp

BotAppSettings = types.BotAppSettings

BotBusinessConnection = types.BotBusinessConnection

BotCommand = types.BotCommand

BotCommandScope = (
    types.BotCommandScopeDefault
    | types.BotCommandScopeUsers
    | types.BotCommandScopeChats
    | types.BotCommandScopeChatAdmins
    | types.BotCommandScopePeer
    | types.BotCommandScopePeerAdmins
    | types.BotCommandScopePeerUser
)

BotInfo = types.BotInfo

BotInlineMessage = (
    types.BotInlineMessageMediaAuto
    | types.BotInlineMessageText
    | types.BotInlineMessageMediaGeo
    | types.BotInlineMessageMediaVenue
    | types.BotInlineMessageMediaContact
    | types.BotInlineMessageMediaInvoice
    | types.BotInlineMessageMediaWebPage
)

BotInlineResult = types.BotInlineResult | types.BotInlineMediaResult

BotMenuButton = (
    types.BotMenuButtonDefault | types.BotMenuButtonCommands | types.BotMenuButton
)

BotPreviewMedia = types.BotPreviewMedia

BotVerification = types.BotVerification

BotVerifierSettings = types.BotVerifierSettings

BusinessAwayMessage = types.BusinessAwayMessage

BusinessAwayMessageSchedule = (
    types.BusinessAwayMessageScheduleAlways
    | types.BusinessAwayMessageScheduleOutsideWorkHours
    | types.BusinessAwayMessageScheduleCustom
)

BusinessBotRecipients = types.BusinessBotRecipients

BusinessBotRights = types.BusinessBotRights

BusinessChatLink = types.BusinessChatLink

BusinessGreetingMessage = types.BusinessGreetingMessage

BusinessIntro = types.BusinessIntro

BusinessLocation = types.BusinessLocation

BusinessRecipients = types.BusinessRecipients

BusinessWeeklyOpen = types.BusinessWeeklyOpen

BusinessWorkHours = types.BusinessWorkHours

CdnConfig = types.CdnConfig

CdnPublicKey = types.CdnPublicKey

ChannelAdminLogEvent = types.ChannelAdminLogEvent

ChannelAdminLogEventAction = (
    types.ChannelAdminLogEventActionChangeTitle
    | types.ChannelAdminLogEventActionChangeAbout
    | types.ChannelAdminLogEventActionChangeUsername
    | types.ChannelAdminLogEventActionChangePhoto
    | types.ChannelAdminLogEventActionToggleInvites
    | types.ChannelAdminLogEventActionToggleSignatures
    | types.ChannelAdminLogEventActionUpdatePinned
    | types.ChannelAdminLogEventActionEditMessage
    | types.ChannelAdminLogEventActionDeleteMessage
    | types.ChannelAdminLogEventActionParticipantJoin
    | types.ChannelAdminLogEventActionParticipantLeave
    | types.ChannelAdminLogEventActionParticipantInvite
    | types.ChannelAdminLogEventActionParticipantToggleBan
    | types.ChannelAdminLogEventActionParticipantToggleAdmin
    | types.ChannelAdminLogEventActionChangeStickerSet
    | types.ChannelAdminLogEventActionTogglePreHistoryHidden
    | types.ChannelAdminLogEventActionDefaultBannedRights
    | types.ChannelAdminLogEventActionStopPoll
    | types.ChannelAdminLogEventActionChangeLinkedChat
    | types.ChannelAdminLogEventActionChangeLocation
    | types.ChannelAdminLogEventActionToggleSlowMode
    | types.ChannelAdminLogEventActionStartGroupCall
    | types.ChannelAdminLogEventActionDiscardGroupCall
    | types.ChannelAdminLogEventActionParticipantMute
    | types.ChannelAdminLogEventActionParticipantUnmute
    | types.ChannelAdminLogEventActionToggleGroupCallSetting
    | types.ChannelAdminLogEventActionParticipantJoinByInvite
    | types.ChannelAdminLogEventActionExportedInviteDelete
    | types.ChannelAdminLogEventActionExportedInviteRevoke
    | types.ChannelAdminLogEventActionExportedInviteEdit
    | types.ChannelAdminLogEventActionParticipantVolume
    | types.ChannelAdminLogEventActionChangeHistoryTtl
    | types.ChannelAdminLogEventActionParticipantJoinByRequest
    | types.ChannelAdminLogEventActionToggleNoForwards
    | types.ChannelAdminLogEventActionSendMessage
    | types.ChannelAdminLogEventActionChangeAvailableReactions
    | types.ChannelAdminLogEventActionChangeUsernames
    | types.ChannelAdminLogEventActionToggleForum
    | types.ChannelAdminLogEventActionCreateTopic
    | types.ChannelAdminLogEventActionEditTopic
    | types.ChannelAdminLogEventActionDeleteTopic
    | types.ChannelAdminLogEventActionPinTopic
    | types.ChannelAdminLogEventActionToggleAntiSpam
    | types.ChannelAdminLogEventActionChangePeerColor
    | types.ChannelAdminLogEventActionChangeProfilePeerColor
    | types.ChannelAdminLogEventActionChangeWallpaper
    | types.ChannelAdminLogEventActionChangeEmojiStatus
    | types.ChannelAdminLogEventActionChangeEmojiStickerSet
    | types.ChannelAdminLogEventActionToggleSignatureProfiles
    | types.ChannelAdminLogEventActionParticipantSubExtend
    | types.ChannelAdminLogEventActionToggleAutotranslation
    | types.ChannelAdminLogEventActionParticipantEditRank
)

ChannelAdminLogEventsFilter = types.ChannelAdminLogEventsFilter

ChannelLocation = types.ChannelLocationEmpty | types.ChannelLocation

ChannelMessagesFilter = types.ChannelMessagesFilterEmpty | types.ChannelMessagesFilter

ChannelParticipant = (
    types.ChannelParticipant
    | types.ChannelParticipantSelf
    | types.ChannelParticipantCreator
    | types.ChannelParticipantAdmin
    | types.ChannelParticipantBanned
    | types.ChannelParticipantLeft
)

ChannelParticipantsFilter = (
    types.ChannelParticipantsRecent
    | types.ChannelParticipantsAdmins
    | types.ChannelParticipantsKicked
    | types.ChannelParticipantsBots
    | types.ChannelParticipantsBanned
    | types.ChannelParticipantsSearch
    | types.ChannelParticipantsContacts
    | types.ChannelParticipantsMentions
)

Chat = (
    types.ChatEmpty
    | types.Chat
    | types.ChatForbidden
    | types.Channel
    | types.ChannelForbidden
)

ChatAdminRights = types.ChatAdminRights

ChatAdminWithInvites = types.ChatAdminWithInvites

ChatBannedRights = types.ChatBannedRights

ChatFull = types.ChatFull | types.ChannelFull

ChatInvite = types.ChatInviteAlready | types.ChatInvite | types.ChatInvitePeek

ChatInviteImporter = types.ChatInviteImporter

ChatOnlines = types.ChatOnlines

ChatParticipant = (
    types.ChatParticipant | types.ChatParticipantCreator | types.ChatParticipantAdmin
)

ChatParticipants = types.ChatParticipantsForbidden | types.ChatParticipants

ChatPhoto = types.ChatPhotoEmpty | types.ChatPhoto

ChatReactions = (
    types.ChatReactionsNone | types.ChatReactionsAll | types.ChatReactionsSome
)

ChatTheme = types.ChatTheme | types.ChatThemeUniqueGift

ClientDhInnerData = types.ClientDhInnerData

CodeSettings = types.CodeSettings

Config = types.Config

ConnectedBot = types.ConnectedBot

ConnectedBotStarRef = types.ConnectedBotStarRef

Contact = types.Contact

ContactBirthday = types.ContactBirthday

ContactStatus = types.ContactStatus

DataJson = types.DataJson

DcOption = types.DcOption

DefaultHistoryTtl = types.DefaultHistoryTtl

DestroyAuthKeyRes = (
    types.DestroyAuthKeyOk | types.DestroyAuthKeyNone | types.DestroyAuthKeyFail
)

DestroySessionRes = types.DestroySessionOk | types.DestroySessionNone

Dialog = types.Dialog | types.DialogFolder

DialogFilter = (
    types.DialogFilter | types.DialogFilterDefault | types.DialogFilterChatlist
)

DialogFilterSuggested = types.DialogFilterSuggested

DialogPeer = types.DialogPeer | types.DialogPeerFolder

DisallowedGiftsSettings = types.DisallowedGiftsSettings

Document = types.DocumentEmpty | types.Document

DocumentAttribute = (
    types.DocumentAttributeImageSize
    | types.DocumentAttributeAnimated
    | types.DocumentAttributeSticker
    | types.DocumentAttributeVideo
    | types.DocumentAttributeAudio
    | types.DocumentAttributeFilename
    | types.DocumentAttributeHasStickers
    | types.DocumentAttributeCustomEmoji
)

DraftMessage = types.DraftMessageEmpty | types.DraftMessage

EmailVerification = (
    types.EmailVerificationCode
    | types.EmailVerificationGoogle
    | types.EmailVerificationApple
)

EmailVerifyPurpose = (
    types.EmailVerifyPurposeLoginSetup
    | types.EmailVerifyPurposeLoginChange
    | types.EmailVerifyPurposePassport
)

EmojiGroup = types.EmojiGroup | types.EmojiGroupGreeting | types.EmojiGroupPremium

EmojiKeyword = types.EmojiKeyword | types.EmojiKeywordDeleted

EmojiKeywordsDifference = types.EmojiKeywordsDifference

EmojiLanguage = types.EmojiLanguage

EmojiList = types.EmojiListNotModified | types.EmojiList

EmojiStatus = (
    types.EmojiStatusEmpty
    | types.EmojiStatus
    | types.EmojiStatusCollectible
    | types.InputEmojiStatusCollectible
)

EmojiUrl = types.EmojiUrl

EncryptedChat = (
    types.EncryptedChatEmpty
    | types.EncryptedChatWaiting
    | types.EncryptedChatRequested
    | types.EncryptedChat
    | types.EncryptedChatDiscarded
)

EncryptedFile = types.EncryptedFileEmpty | types.EncryptedFile

EncryptedMessage = types.EncryptedMessage | types.EncryptedMessageService

Error = types.Error

ExportedChatInvite = types.ChatInviteExported | types.ChatInvitePublicJoinRequests

ExportedChatlistInvite = types.ExportedChatlistInvite

ExportedContactToken = types.ExportedContactToken

ExportedMessageLink = types.ExportedMessageLink

ExportedStoryLink = types.ExportedStoryLink

FactCheck = types.FactCheck

FileHash = types.FileHash

Folder = types.Folder

FolderPeer = types.FolderPeer

ForumTopic = types.ForumTopicDeleted | types.ForumTopic

FoundStory = types.FoundStory

FutureSalt = types.FutureSalt

FutureSalts = types.FutureSalts

Game = types.Game

GeoPoint = types.GeoPointEmpty | types.GeoPoint

GeoPointAddress = types.GeoPointAddress

GlobalPrivacySettings = types.GlobalPrivacySettings

GroupCall = types.GroupCallDiscarded | types.GroupCall

GroupCallDonor = types.GroupCallDonor

GroupCallMessage = types.GroupCallMessage

GroupCallParticipant = types.GroupCallParticipant

GroupCallParticipantVideo = types.GroupCallParticipantVideo

GroupCallParticipantVideoSourceGroup = types.GroupCallParticipantVideoSourceGroup

GroupCallStreamChannel = types.GroupCallStreamChannel

HighScore = types.HighScore

HttpWait = types.HttpWait

ImportedContact = types.ImportedContact

InlineBotSwitchPm = types.InlineBotSwitchPm

InlineBotWebView = types.InlineBotWebView

InlineQueryPeerType = (
    types.InlineQueryPeerTypeSameBotPm
    | types.InlineQueryPeerTypePm
    | types.InlineQueryPeerTypeChat
    | types.InlineQueryPeerTypeMegagroup
    | types.InlineQueryPeerTypeBroadcast
    | types.InlineQueryPeerTypeBotPm
)

InputAiComposeTone = (
    types.InputAiComposeToneDefault
    | types.InputAiComposeToneId
    | types.InputAiComposeToneSlug
)

InputAppEvent = types.InputAppEvent

InputBotApp = types.InputBotAppId | types.InputBotAppShortName

InputBotInlineMessage = (
    types.InputBotInlineMessageMediaAuto
    | types.InputBotInlineMessageText
    | types.InputBotInlineMessageMediaGeo
    | types.InputBotInlineMessageMediaVenue
    | types.InputBotInlineMessageMediaContact
    | types.InputBotInlineMessageGame
    | types.InputBotInlineMessageMediaInvoice
    | types.InputBotInlineMessageMediaWebPage
)

InputBotInlineMessageId = (
    types.InputBotInlineMessageId | types.InputBotInlineMessageId64
)

InputBotInlineResult = (
    types.InputBotInlineResult
    | types.InputBotInlineResultPhoto
    | types.InputBotInlineResultDocument
    | types.InputBotInlineResultGame
)

InputBusinessAwayMessage = types.InputBusinessAwayMessage

InputBusinessBotRecipients = types.InputBusinessBotRecipients

InputBusinessChatLink = types.InputBusinessChatLink

InputBusinessGreetingMessage = types.InputBusinessGreetingMessage

InputBusinessIntro = types.InputBusinessIntro

InputBusinessRecipients = types.InputBusinessRecipients

InputChannel = (
    types.InputChannelEmpty | types.InputChannel | types.InputChannelFromMessage
)

InputChatPhoto = (
    types.InputChatPhotoEmpty | types.InputChatUploadedPhoto | types.InputChatPhoto
)

InputChatTheme = (
    types.InputChatThemeEmpty | types.InputChatTheme | types.InputChatThemeUniqueGift
)

InputChatlist = types.InputChatlistDialogFilter

InputCheckPasswordSrp = types.InputCheckPasswordEmpty | types.InputCheckPasswordSrp

InputClientProxy = types.InputClientProxy

InputCollectible = types.InputCollectibleUsername | types.InputCollectiblePhone

InputContact = types.InputPhoneContact

InputDialogPeer = types.InputDialogPeer | types.InputDialogPeerFolder

InputDocument = types.InputDocumentEmpty | types.InputDocument

InputEncryptedChat = types.InputEncryptedChat

InputEncryptedFile = (
    types.InputEncryptedFileEmpty
    | types.InputEncryptedFileUploaded
    | types.InputEncryptedFile
    | types.InputEncryptedFileBigUploaded
)

InputFile = types.InputFile | types.InputFileBig | types.InputFileStoryDocument

InputFileLocation = (
    types.InputFileLocation
    | types.InputEncryptedFileLocation
    | types.InputDocumentFileLocation
    | types.InputSecureFileLocation
    | types.InputTakeoutFileLocation
    | types.InputPhotoFileLocation
    | types.InputPhotoLegacyFileLocation
    | types.InputPeerPhotoFileLocation
    | types.InputStickerSetThumb
    | types.InputGroupCallStream
)

InputFolderPeer = types.InputFolderPeer

InputGame = types.InputGameId | types.InputGameShortName

InputGeoPoint = types.InputGeoPointEmpty | types.InputGeoPoint

InputGroupCall = (
    types.InputGroupCall | types.InputGroupCallSlug | types.InputGroupCallInviteMessage
)

InputInvoice = (
    types.InputInvoiceMessage
    | types.InputInvoiceSlug
    | types.InputInvoicePremiumGiftCode
    | types.InputInvoiceStars
    | types.InputInvoiceChatInviteSubscription
    | types.InputInvoiceStarGift
    | types.InputInvoiceStarGiftUpgrade
    | types.InputInvoiceStarGiftTransfer
    | types.InputInvoicePremiumGiftStars
    | types.InputInvoiceBusinessBotTransferStars
    | types.InputInvoiceStarGiftResale
    | types.InputInvoiceStarGiftPrepaidUpgrade
    | types.InputInvoicePremiumAuthCode
    | types.InputInvoiceStarGiftDropOriginalDetails
    | types.InputInvoiceStarGiftAuctionBid
)

InputMedia = (
    types.InputMediaEmpty
    | types.InputMediaUploadedPhoto
    | types.InputMediaPhoto
    | types.InputMediaGeoPoint
    | types.InputMediaContact
    | types.InputMediaUploadedDocument
    | types.InputMediaDocument
    | types.InputMediaVenue
    | types.InputMediaPhotoExternal
    | types.InputMediaDocumentExternal
    | types.InputMediaGame
    | types.InputMediaInvoice
    | types.InputMediaGeoLive
    | types.InputMediaPoll
    | types.InputMediaDice
    | types.InputMediaStory
    | types.InputMediaWebPage
    | types.InputMediaPaidMedia
    | types.InputMediaTodo
    | types.InputMediaStakeDice
)

InputMessage = (
    types.InputMessageId
    | types.InputMessageReplyTo
    | types.InputMessagePinned
    | types.InputMessageCallbackQuery
)

InputMessageReadMetric = types.InputMessageReadMetric

InputNotifyPeer = (
    types.InputNotifyPeer
    | types.InputNotifyUsers
    | types.InputNotifyChats
    | types.InputNotifyBroadcasts
    | types.InputNotifyForumTopic
)

InputPasskeyCredential = (
    types.InputPasskeyCredentialPublicKey | types.InputPasskeyCredentialFirebasePnv
)

InputPasskeyResponse = (
    types.InputPasskeyResponseRegister | types.InputPasskeyResponseLogin
)

InputPaymentCredentials = (
    types.InputPaymentCredentialsSaved
    | types.InputPaymentCredentials
    | types.InputPaymentCredentialsApplePay
    | types.InputPaymentCredentialsGooglePay
)

InputPeer = (
    types.InputPeerEmpty
    | types.InputPeerSelf
    | types.InputPeerChat
    | types.InputPeerUser
    | types.InputPeerChannel
    | types.InputPeerUserFromMessage
    | types.InputPeerChannelFromMessage
)

InputPeerNotifySettings = types.InputPeerNotifySettings

InputPhoneCall = types.InputPhoneCall

InputPhoto = types.InputPhotoEmpty | types.InputPhoto

InputPrivacyKey = (
    types.InputPrivacyKeyStatusTimestamp
    | types.InputPrivacyKeyChatInvite
    | types.InputPrivacyKeyPhoneCall
    | types.InputPrivacyKeyPhoneP2P
    | types.InputPrivacyKeyForwards
    | types.InputPrivacyKeyProfilePhoto
    | types.InputPrivacyKeyPhoneNumber
    | types.InputPrivacyKeyAddedByPhone
    | types.InputPrivacyKeyVoiceMessages
    | types.InputPrivacyKeyAbout
    | types.InputPrivacyKeyBirthday
    | types.InputPrivacyKeyStarGiftsAutoSave
    | types.InputPrivacyKeyNoPaidMessages
    | types.InputPrivacyKeySavedMusic
)

InputPrivacyRule = (
    types.InputPrivacyValueAllowContacts
    | types.InputPrivacyValueAllowAll
    | types.InputPrivacyValueAllowUsers
    | types.InputPrivacyValueDisallowContacts
    | types.InputPrivacyValueDisallowAll
    | types.InputPrivacyValueDisallowUsers
    | types.InputPrivacyValueAllowChatParticipants
    | types.InputPrivacyValueDisallowChatParticipants
    | types.InputPrivacyValueAllowCloseFriends
    | types.InputPrivacyValueAllowPremium
    | types.InputPrivacyValueAllowBots
    | types.InputPrivacyValueDisallowBots
)

InputQuickReplyShortcut = (
    types.InputQuickReplyShortcut | types.InputQuickReplyShortcutId
)

InputReplyTo = (
    types.InputReplyToMessage | types.InputReplyToStory | types.InputReplyToMonoForum
)

InputSavedStarGift = (
    types.InputSavedStarGiftUser
    | types.InputSavedStarGiftChat
    | types.InputSavedStarGiftSlug
)

InputSecureFile = types.InputSecureFileUploaded | types.InputSecureFile

InputSecureValue = types.InputSecureValue

InputSingleMedia = types.InputSingleMedia

InputStarGiftAuction = types.InputStarGiftAuction | types.InputStarGiftAuctionSlug

InputStarsTransaction = types.InputStarsTransaction

InputStickerSet = (
    types.InputStickerSetEmpty
    | types.InputStickerSetId
    | types.InputStickerSetShortName
    | types.InputStickerSetAnimatedEmoji
    | types.InputStickerSetDice
    | types.InputStickerSetAnimatedEmojiAnimations
    | types.InputStickerSetPremiumGifts
    | types.InputStickerSetEmojiGenericAnimations
    | types.InputStickerSetEmojiDefaultStatuses
    | types.InputStickerSetEmojiDefaultTopicIcons
    | types.InputStickerSetEmojiChannelDefaultStatuses
    | types.InputStickerSetTonGifts
)

InputStickerSetItem = types.InputStickerSetItem

InputStickeredMedia = types.InputStickeredMediaPhoto | types.InputStickeredMediaDocument

InputStorePaymentPurpose = (
    types.InputStorePaymentPremiumSubscription
    | types.InputStorePaymentGiftPremium
    | types.InputStorePaymentPremiumGiftCode
    | types.InputStorePaymentPremiumGiveaway
    | types.InputStorePaymentStarsTopup
    | types.InputStorePaymentStarsGift
    | types.InputStorePaymentStarsGiveaway
    | types.InputStorePaymentAuthCode
)

InputTheme = types.InputTheme | types.InputThemeSlug

InputThemeSettings = types.InputThemeSettings

InputUser = (
    types.InputUserEmpty
    | types.InputUserSelf
    | types.InputUser
    | types.InputUserFromMessage
)

InputWallPaper = (
    types.InputWallPaper | types.InputWallPaperSlug | types.InputWallPaperNoFile
)

InputWebDocument = types.InputWebDocument

InputWebFileLocation = (
    types.InputWebFileLocation
    | types.InputWebFileGeoPointLocation
    | types.InputWebFileAudioAlbumThumbLocation
)

Invoice = types.Invoice

IpPort = types.IpPort | types.IpPortSecret

JsonobjectValue = types.JsonObjectValue

Jsonvalue = (
    types.JsonNull
    | types.JsonBool
    | types.JsonNumber
    | types.JsonString
    | types.JsonArray
    | types.JsonObject
)

KeyboardButton = (
    types.KeyboardButton
    | types.KeyboardButtonUrl
    | types.KeyboardButtonCallback
    | types.KeyboardButtonRequestPhone
    | types.KeyboardButtonRequestGeoLocation
    | types.KeyboardButtonSwitchInline
    | types.KeyboardButtonGame
    | types.KeyboardButtonBuy
    | types.KeyboardButtonUrlAuth
    | types.InputKeyboardButtonUrlAuth
    | types.KeyboardButtonRequestPoll
    | types.InputKeyboardButtonUserProfile
    | types.KeyboardButtonUserProfile
    | types.KeyboardButtonWebView
    | types.KeyboardButtonSimpleWebView
    | types.KeyboardButtonRequestPeer
    | types.InputKeyboardButtonRequestPeer
    | types.KeyboardButtonCopy
)

KeyboardButtonRow = types.KeyboardButtonRow

KeyboardButtonStyle = types.KeyboardButtonStyle

LabeledPrice = types.LabeledPrice

LangPackDifference = types.LangPackDifference

LangPackLanguage = types.LangPackLanguage

LangPackString = (
    types.LangPackString | types.LangPackStringPluralized | types.LangPackStringDeleted
)

MaskCoords = types.MaskCoords

MediaArea = (
    types.MediaAreaVenue
    | types.InputMediaAreaVenue
    | types.MediaAreaGeoPoint
    | types.MediaAreaSuggestedReaction
    | types.MediaAreaChannelPost
    | types.InputMediaAreaChannelPost
    | types.MediaAreaUrl
    | types.MediaAreaWeather
    | types.MediaAreaStarGift
)

MediaAreaCoordinates = types.MediaAreaCoordinates

Message = types.MessageEmpty | types.Message | types.MessageService

MessageAction = (
    types.MessageActionEmpty
    | types.MessageActionChatCreate
    | types.MessageActionChatEditTitle
    | types.MessageActionChatEditPhoto
    | types.MessageActionChatDeletePhoto
    | types.MessageActionChatAddUser
    | types.MessageActionChatDeleteUser
    | types.MessageActionChatJoinedByLink
    | types.MessageActionChannelCreate
    | types.MessageActionChatMigrateTo
    | types.MessageActionChannelMigrateFrom
    | types.MessageActionPinMessage
    | types.MessageActionHistoryClear
    | types.MessageActionGameScore
    | types.MessageActionPaymentSentMe
    | types.MessageActionPaymentSent
    | types.MessageActionPhoneCall
    | types.MessageActionScreenshotTaken
    | types.MessageActionCustomAction
    | types.MessageActionBotAllowed
    | types.MessageActionSecureValuesSentMe
    | types.MessageActionSecureValuesSent
    | types.MessageActionContactSignUp
    | types.MessageActionGeoProximityReached
    | types.MessageActionGroupCall
    | types.MessageActionInviteToGroupCall
    | types.MessageActionSetMessagesTtl
    | types.MessageActionGroupCallScheduled
    | types.MessageActionSetChatTheme
    | types.MessageActionChatJoinedByRequest
    | types.MessageActionWebViewDataSentMe
    | types.MessageActionWebViewDataSent
    | types.MessageActionGiftPremium
    | types.MessageActionTopicCreate
    | types.MessageActionTopicEdit
    | types.MessageActionSuggestProfilePhoto
    | types.MessageActionRequestedPeer
    | types.MessageActionSetChatWallPaper
    | types.MessageActionGiftCode
    | types.MessageActionGiveawayLaunch
    | types.MessageActionGiveawayResults
    | types.MessageActionBoostApply
    | types.MessageActionRequestedPeerSentMe
    | types.MessageActionPaymentRefunded
    | types.MessageActionGiftStars
    | types.MessageActionPrizeStars
    | types.MessageActionStarGift
    | types.MessageActionStarGiftUnique
    | types.MessageActionPaidMessagesRefunded
    | types.MessageActionPaidMessagesPrice
    | types.MessageActionConferenceCall
    | types.MessageActionTodoCompletions
    | types.MessageActionTodoAppendTasks
    | types.MessageActionSuggestedPostApproval
    | types.MessageActionSuggestedPostSuccess
    | types.MessageActionSuggestedPostRefund
    | types.MessageActionGiftTon
    | types.MessageActionSuggestBirthday
    | types.MessageActionStarGiftPurchaseOffer
    | types.MessageActionStarGiftPurchaseOfferDeclined
    | types.MessageActionNewCreatorPending
    | types.MessageActionChangeCreator
    | types.MessageActionNoForwardsToggle
    | types.MessageActionNoForwardsRequest
    | types.MessageActionPollAppendAnswer
    | types.MessageActionPollDeleteAnswer
    | types.MessageActionManagedBotCreated
)

MessageEntity = (
    types.MessageEntityUnknown
    | types.MessageEntityMention
    | types.MessageEntityHashtag
    | types.MessageEntityBotCommand
    | types.MessageEntityUrl
    | types.MessageEntityEmail
    | types.MessageEntityBold
    | types.MessageEntityItalic
    | types.MessageEntityCode
    | types.MessageEntityPre
    | types.MessageEntityTextUrl
    | types.MessageEntityMentionName
    | types.InputMessageEntityMentionName
    | types.MessageEntityPhone
    | types.MessageEntityCashtag
    | types.MessageEntityUnderline
    | types.MessageEntityStrike
    | types.MessageEntityBankCard
    | types.MessageEntitySpoiler
    | types.MessageEntityCustomEmoji
    | types.MessageEntityBlockquote
    | types.MessageEntityFormattedDate
    | types.MessageEntityDiffInsert
    | types.MessageEntityDiffReplace
    | types.MessageEntityDiffDelete
)

MessageExtendedMedia = types.MessageExtendedMediaPreview | types.MessageExtendedMedia

MessageFwdHeader = types.MessageFwdHeader

MessageMedia = (
    types.MessageMediaEmpty
    | types.MessageMediaPhoto
    | types.MessageMediaGeo
    | types.MessageMediaContact
    | types.MessageMediaUnsupported
    | types.MessageMediaDocument
    | types.MessageMediaWebPage
    | types.MessageMediaVenue
    | types.MessageMediaGame
    | types.MessageMediaInvoice
    | types.MessageMediaGeoLive
    | types.MessageMediaPoll
    | types.MessageMediaDice
    | types.MessageMediaStory
    | types.MessageMediaGiveaway
    | types.MessageMediaGiveawayResults
    | types.MessageMediaPaidMedia
    | types.MessageMediaToDo
    | types.MessageMediaVideoStream
)

MessagePeerReaction = types.MessagePeerReaction

MessagePeerVote = (
    types.MessagePeerVote
    | types.MessagePeerVoteInputOption
    | types.MessagePeerVoteMultiple
)

MessageRange = types.MessageRange

MessageReactions = types.MessageReactions

MessageReactor = types.MessageReactor

MessageReplies = types.MessageReplies

MessageReplyHeader = types.MessageReplyHeader | types.MessageReplyStoryHeader

MessageReportOption = types.MessageReportOption

MessageViews = types.MessageViews

MessagesFilter = (
    types.InputMessagesFilterEmpty
    | types.InputMessagesFilterPhotos
    | types.InputMessagesFilterVideo
    | types.InputMessagesFilterPhotoVideo
    | types.InputMessagesFilterDocument
    | types.InputMessagesFilterUrl
    | types.InputMessagesFilterGif
    | types.InputMessagesFilterVoice
    | types.InputMessagesFilterMusic
    | types.InputMessagesFilterChatPhotos
    | types.InputMessagesFilterPhoneCalls
    | types.InputMessagesFilterRoundVoice
    | types.InputMessagesFilterRoundVideo
    | types.InputMessagesFilterMyMentions
    | types.InputMessagesFilterGeo
    | types.InputMessagesFilterContacts
    | types.InputMessagesFilterPinned
    | types.InputMessagesFilterPoll
)

MissingInvitee = types.MissingInvitee

MsgDetailedInfo = types.MsgDetailedInfo | types.MsgNewDetailedInfo

MsgResendReq = types.MsgResendReq | types.MsgResendAnsReq

MsgsAck = types.MsgsAck

MsgsAllInfo = types.MsgsAllInfo

MsgsStateInfo = types.MsgsStateInfo

MsgsStateReq = types.MsgsStateReq

MyBoost = types.MyBoost

NearestDc = types.NearestDc

NewSession = types.NewSessionCreated

NotificationSound = (
    types.NotificationSoundDefault
    | types.NotificationSoundNone
    | types.NotificationSoundLocal
    | types.NotificationSoundRingtone
)

NotifyPeer = (
    types.NotifyPeer
    | types.NotifyUsers
    | types.NotifyChats
    | types.NotifyBroadcasts
    | types.NotifyForumTopic
)

Null = types.Null

OutboxReadDate = types.OutboxReadDate

PQInnerData = (
    types.PQInnerData
    | types.PQInnerDataDc
    | types.PQInnerDataTemp
    | types.PQInnerDataTempDc
)

Page = types.Page

PageBlock = (
    types.PageBlockUnsupported
    | types.PageBlockTitle
    | types.PageBlockSubtitle
    | types.PageBlockAuthorDate
    | types.PageBlockHeader
    | types.PageBlockSubheader
    | types.PageBlockParagraph
    | types.PageBlockPreformatted
    | types.PageBlockFooter
    | types.PageBlockDivider
    | types.PageBlockAnchor
    | types.PageBlockList
    | types.PageBlockBlockquote
    | types.PageBlockPullquote
    | types.PageBlockPhoto
    | types.PageBlockVideo
    | types.PageBlockCover
    | types.PageBlockEmbed
    | types.PageBlockEmbedPost
    | types.PageBlockCollage
    | types.PageBlockSlideshow
    | types.PageBlockChannel
    | types.PageBlockAudio
    | types.PageBlockKicker
    | types.PageBlockTable
    | types.PageBlockOrderedList
    | types.PageBlockDetails
    | types.PageBlockRelatedArticles
    | types.PageBlockMap
)

PageCaption = types.PageCaption

PageListItem = types.PageListItemText | types.PageListItemBlocks

PageListOrderedItem = types.PageListOrderedItemText | types.PageListOrderedItemBlocks

PageRelatedArticle = types.PageRelatedArticle

PageTableCell = types.PageTableCell

PageTableRow = types.PageTableRow

PaidReactionPrivacy = (
    types.PaidReactionPrivacyDefault
    | types.PaidReactionPrivacyAnonymous
    | types.PaidReactionPrivacyPeer
)

Passkey = types.Passkey

PasswordKdfAlgo = (
    types.PasswordKdfAlgoUnknown
    | types.PasswordKdfAlgoSha256Sha256Pbkdf2Hmacsha512iter100000Sha256ModPow
)

PaymentCharge = types.PaymentCharge

PaymentFormMethod = types.PaymentFormMethod

PaymentRequestedInfo = types.PaymentRequestedInfo

PaymentSavedCredentials = types.PaymentSavedCredentialsCard

Peer = types.PeerUser | types.PeerChat | types.PeerChannel

PeerBlocked = types.PeerBlocked

PeerColor = (
    types.PeerColor | types.PeerColorCollectible | types.InputPeerColorCollectible
)

PeerLocated = types.PeerLocated | types.PeerSelfLocated

PeerNotifySettings = types.PeerNotifySettings

PeerSettings = types.PeerSettings

PeerStories = types.PeerStories

PendingSuggestion = types.PendingSuggestion

PhoneCall = (
    types.PhoneCallEmpty
    | types.PhoneCallWaiting
    | types.PhoneCallRequested
    | types.PhoneCallAccepted
    | types.PhoneCall
    | types.PhoneCallDiscarded
)

PhoneCallDiscardReason = (
    types.PhoneCallDiscardReasonMissed
    | types.PhoneCallDiscardReasonDisconnect
    | types.PhoneCallDiscardReasonHangup
    | types.PhoneCallDiscardReasonBusy
    | types.PhoneCallDiscardReasonMigrateConferenceCall
)

PhoneCallProtocol = types.PhoneCallProtocol

PhoneConnection = types.PhoneConnection | types.PhoneConnectionWebrtc

Photo = types.PhotoEmpty | types.Photo

PhotoSize = (
    types.PhotoSizeEmpty
    | types.PhotoSize
    | types.PhotoCachedSize
    | types.PhotoStrippedSize
    | types.PhotoSizeProgressive
    | types.PhotoPathSize
)

Poll = types.Poll

PollAnswer = types.PollAnswer | types.InputPollAnswer

PollAnswerVoters = types.PollAnswerVoters

PollResults = types.PollResults

Pong = types.Pong

PopularContact = types.PopularContact

PostAddress = types.PostAddress

PostInteractionCounters = (
    types.PostInteractionCountersMessage | types.PostInteractionCountersStory
)

PremiumGiftCodeOption = types.PremiumGiftCodeOption

PremiumSubscriptionOption = types.PremiumSubscriptionOption

PrepaidGiveaway = types.PrepaidGiveaway | types.PrepaidStarsGiveaway

PrivacyKey = (
    types.PrivacyKeyStatusTimestamp
    | types.PrivacyKeyChatInvite
    | types.PrivacyKeyPhoneCall
    | types.PrivacyKeyPhoneP2P
    | types.PrivacyKeyForwards
    | types.PrivacyKeyProfilePhoto
    | types.PrivacyKeyPhoneNumber
    | types.PrivacyKeyAddedByPhone
    | types.PrivacyKeyVoiceMessages
    | types.PrivacyKeyAbout
    | types.PrivacyKeyBirthday
    | types.PrivacyKeyStarGiftsAutoSave
    | types.PrivacyKeyNoPaidMessages
    | types.PrivacyKeySavedMusic
)

PrivacyRule = (
    types.PrivacyValueAllowContacts
    | types.PrivacyValueAllowAll
    | types.PrivacyValueAllowUsers
    | types.PrivacyValueDisallowContacts
    | types.PrivacyValueDisallowAll
    | types.PrivacyValueDisallowUsers
    | types.PrivacyValueAllowChatParticipants
    | types.PrivacyValueDisallowChatParticipants
    | types.PrivacyValueAllowCloseFriends
    | types.PrivacyValueAllowPremium
    | types.PrivacyValueAllowBots
    | types.PrivacyValueDisallowBots
)

ProfileTab = (
    types.ProfileTabPosts
    | types.ProfileTabGifts
    | types.ProfileTabMedia
    | types.ProfileTabFiles
    | types.ProfileTabMusic
    | types.ProfileTabVoice
    | types.ProfileTabLinks
    | types.ProfileTabGifs
)

PublicForward = types.PublicForwardMessage | types.PublicForwardStory

QuickReply = types.QuickReply

Reaction = (
    types.ReactionEmpty
    | types.ReactionEmoji
    | types.ReactionCustomEmoji
    | types.ReactionPaid
)

ReactionCount = types.ReactionCount

ReactionNotificationsFrom = (
    types.ReactionNotificationsFromContacts | types.ReactionNotificationsFromAll
)

ReactionsNotifySettings = types.ReactionsNotifySettings

ReadParticipantDate = types.ReadParticipantDate

ReceivedNotifyMessage = types.ReceivedNotifyMessage

RecentMeUrl = (
    types.RecentMeUrlUnknown
    | types.RecentMeUrlUser
    | types.RecentMeUrlChat
    | types.RecentMeUrlChatInvite
    | types.RecentMeUrlStickerSet
)

RecentStory = types.RecentStory

ReplyMarkup = (
    types.ReplyKeyboardHide
    | types.ReplyKeyboardForceReply
    | types.ReplyKeyboardMarkup
    | types.ReplyInlineMarkup
)

ReportReason = (
    types.InputReportReasonSpam
    | types.InputReportReasonViolence
    | types.InputReportReasonPornography
    | types.InputReportReasonChildAbuse
    | types.InputReportReasonOther
    | types.InputReportReasonCopyright
    | types.InputReportReasonGeoIrrelevant
    | types.InputReportReasonFake
    | types.InputReportReasonIllegalDrugs
    | types.InputReportReasonPersonalDetails
)

ReportResult = (
    types.ReportResultChooseOption
    | types.ReportResultAddComment
    | types.ReportResultReported
)

RequestPeerType = (
    types.RequestPeerTypeUser
    | types.RequestPeerTypeChat
    | types.RequestPeerTypeBroadcast
    | types.RequestPeerTypeCreateBot
)

RequestedPeer = (
    types.RequestedPeerUser | types.RequestedPeerChat | types.RequestedPeerChannel
)

RequirementToContact = (
    types.RequirementToContactEmpty
    | types.RequirementToContactPremium
    | types.RequirementToContactPaidMessages
)

ResPq = types.ResPq

RestrictionReason = types.RestrictionReason

RichText = (
    types.TextEmpty
    | types.TextPlain
    | types.TextBold
    | types.TextItalic
    | types.TextUnderline
    | types.TextStrike
    | types.TextFixed
    | types.TextUrl
    | types.TextEmail
    | types.TextConcat
    | types.TextSubscript
    | types.TextSuperscript
    | types.TextMarked
    | types.TextPhone
    | types.TextImage
    | types.TextAnchor
)

RpcDropAnswer = (
    types.RpcAnswerUnknown | types.RpcAnswerDroppedRunning | types.RpcAnswerDropped
)

RpcError = types.RpcError

SavedContact = types.SavedPhoneContact

SavedDialog = types.SavedDialog | types.MonoForumDialog

SavedReactionTag = types.SavedReactionTag

SavedStarGift = types.SavedStarGift

SearchPostsFlood = types.SearchPostsFlood

SearchResultsCalendarPeriod = types.SearchResultsCalendarPeriod

SearchResultsPosition = types.SearchResultPosition

SecureCredentialsEncrypted = types.SecureCredentialsEncrypted

SecureData = types.SecureData

SecureFile = types.SecureFileEmpty | types.SecureFile

SecurePasswordKdfAlgo = (
    types.SecurePasswordKdfAlgoUnknown
    | types.SecurePasswordKdfAlgoPbkdf2Hmacsha512iter100000
    | types.SecurePasswordKdfAlgoSha512
)

SecurePlainData = types.SecurePlainPhone | types.SecurePlainEmail

SecureRequiredType = types.SecureRequiredType | types.SecureRequiredTypeOneOf

SecureSecretSettings = types.SecureSecretSettings

SecureValue = types.SecureValue

SecureValueError = (
    types.SecureValueErrorData
    | types.SecureValueErrorFrontSide
    | types.SecureValueErrorReverseSide
    | types.SecureValueErrorSelfie
    | types.SecureValueErrorFile
    | types.SecureValueErrorFiles
    | types.SecureValueError
    | types.SecureValueErrorTranslationFile
    | types.SecureValueErrorTranslationFiles
)

SecureValueHash = types.SecureValueHash

SecureValueType = (
    types.SecureValueTypePersonalDetails
    | types.SecureValueTypePassport
    | types.SecureValueTypeDriverLicense
    | types.SecureValueTypeIdentityCard
    | types.SecureValueTypeInternalPassport
    | types.SecureValueTypeAddress
    | types.SecureValueTypeUtilityBill
    | types.SecureValueTypeBankStatement
    | types.SecureValueTypeRentalAgreement
    | types.SecureValueTypePassportRegistration
    | types.SecureValueTypeTemporaryRegistration
    | types.SecureValueTypePhone
    | types.SecureValueTypeEmail
)

SendAsPeer = types.SendAsPeer

SendMessageAction = (
    types.SendMessageTypingAction
    | types.SendMessageCancelAction
    | types.SendMessageRecordVideoAction
    | types.SendMessageUploadVideoAction
    | types.SendMessageRecordAudioAction
    | types.SendMessageUploadAudioAction
    | types.SendMessageUploadPhotoAction
    | types.SendMessageUploadDocumentAction
    | types.SendMessageGeoLocationAction
    | types.SendMessageChooseContactAction
    | types.SendMessageGamePlayAction
    | types.SendMessageRecordRoundAction
    | types.SendMessageUploadRoundAction
    | types.SpeakingInGroupCallAction
    | types.SendMessageHistoryImportAction
    | types.SendMessageChooseStickerAction
    | types.SendMessageEmojiInteraction
    | types.SendMessageEmojiInteractionSeen
    | types.SendMessageTextDraftAction
)

ServerDhParams = types.ServerDhParamsFail | types.ServerDhParamsOk

ServerDhInnerData = types.ServerDhInnerData

SetClientDhParamsAnswer = types.DhGenOk | types.DhGenRetry | types.DhGenFail

ShippingOption = types.ShippingOption

SmsJob = types.SmsJob

SponsoredMessage = types.SponsoredMessage

SponsoredMessageReportOption = types.SponsoredMessageReportOption

SponsoredPeer = types.SponsoredPeer

StarGift = types.StarGift | types.StarGiftUnique

StarGiftActiveAuctionState = types.StarGiftActiveAuctionState

StarGiftAttribute = (
    types.StarGiftAttributeModel
    | types.StarGiftAttributePattern
    | types.StarGiftAttributeBackdrop
    | types.StarGiftAttributeOriginalDetails
)

StarGiftAttributeCounter = types.StarGiftAttributeCounter

StarGiftAttributeId = (
    types.StarGiftAttributeIdModel
    | types.StarGiftAttributeIdPattern
    | types.StarGiftAttributeIdBackdrop
)

StarGiftAttributeRarity = (
    types.StarGiftAttributeRarity
    | types.StarGiftAttributeRarityUncommon
    | types.StarGiftAttributeRarityRare
    | types.StarGiftAttributeRarityEpic
    | types.StarGiftAttributeRarityLegendary
)

StarGiftAuctionAcquiredGift = types.StarGiftAuctionAcquiredGift

StarGiftAuctionRound = types.StarGiftAuctionRound | types.StarGiftAuctionRoundExtendable

StarGiftAuctionState = (
    types.StarGiftAuctionStateNotModified
    | types.StarGiftAuctionState
    | types.StarGiftAuctionStateFinished
)

StarGiftAuctionUserState = types.StarGiftAuctionUserState

StarGiftBackground = types.StarGiftBackground

StarGiftCollection = types.StarGiftCollection

StarGiftUpgradePrice = types.StarGiftUpgradePrice

StarRefProgram = types.StarRefProgram

StarsAmount = types.StarsAmount | types.StarsTonAmount

StarsGiftOption = types.StarsGiftOption

StarsGiveawayOption = types.StarsGiveawayOption

StarsGiveawayWinnersOption = types.StarsGiveawayWinnersOption

StarsRating = types.StarsRating

StarsRevenueStatus = types.StarsRevenueStatus

StarsSubscription = types.StarsSubscription

StarsSubscriptionPricing = types.StarsSubscriptionPricing

StarsTopupOption = types.StarsTopupOption

StarsTransaction = types.StarsTransaction

StarsTransactionPeer = (
    types.StarsTransactionPeerUnsupported
    | types.StarsTransactionPeerAppStore
    | types.StarsTransactionPeerPlayMarket
    | types.StarsTransactionPeerPremiumBot
    | types.StarsTransactionPeerFragment
    | types.StarsTransactionPeer
    | types.StarsTransactionPeerAds
    | types.StarsTransactionPeerApi
)

StatsAbsValueAndPrev = types.StatsAbsValueAndPrev

StatsDateRangeDays = types.StatsDateRangeDays

StatsGraph = types.StatsGraphAsync | types.StatsGraphError | types.StatsGraph

StatsGroupTopAdmin = types.StatsGroupTopAdmin

StatsGroupTopInviter = types.StatsGroupTopInviter

StatsGroupTopPoster = types.StatsGroupTopPoster

StatsPercentValue = types.StatsPercentValue

StatsUrl = types.StatsUrl

StickerKeyword = types.StickerKeyword

StickerPack = types.StickerPack

StickerSet = types.StickerSet

StickerSetCovered = (
    types.StickerSetCovered
    | types.StickerSetMultiCovered
    | types.StickerSetFullCovered
    | types.StickerSetNoCovered
)

StoriesStealthMode = types.StoriesStealthMode

StoryAlbum = types.StoryAlbum

StoryFwdHeader = types.StoryFwdHeader

StoryItem = types.StoryItemDeleted | types.StoryItemSkipped | types.StoryItem

StoryReaction = (
    types.StoryReaction
    | types.StoryReactionPublicForward
    | types.StoryReactionPublicRepost
)

StoryView = types.StoryView | types.StoryViewPublicForward | types.StoryViewPublicRepost

StoryViews = types.StoryViews

SuggestedPost = types.SuggestedPost

TextWithEntities = types.TextWithEntities

Theme = types.Theme

ThemeSettings = types.ThemeSettings

Timezone = types.Timezone

TlsBlock = (
    types.TlsBlockString
    | types.TlsBlockRandom
    | types.TlsBlockZero
    | types.TlsBlockDomain
    | types.TlsBlockGrease
    | types.TlsBlockPublicKey
    | types.TlsBlockScope
)

TlsClientHello = types.TlsClientHello

TodoCompletion = types.TodoCompletion

TodoItem = types.TodoItem

TodoList = types.TodoList

TopPeer = types.TopPeer

TopPeerCategory = (
    types.TopPeerCategoryBotsPm
    | types.TopPeerCategoryBotsInline
    | types.TopPeerCategoryCorrespondents
    | types.TopPeerCategoryGroups
    | types.TopPeerCategoryChannels
    | types.TopPeerCategoryPhoneCalls
    | types.TopPeerCategoryForwardUsers
    | types.TopPeerCategoryForwardChats
    | types.TopPeerCategoryBotsApp
    | types.TopPeerCategoryBotsGuestChat
)

TopPeerCategoryPeers = types.TopPeerCategoryPeers

Update = (
    types.UpdateNewMessage
    | types.UpdateMessageId
    | types.UpdateDeleteMessages
    | types.UpdateUserTyping
    | types.UpdateChatUserTyping
    | types.UpdateChatParticipants
    | types.UpdateUserStatus
    | types.UpdateUserName
    | types.UpdateNewAuthorization
    | types.UpdateNewEncryptedMessage
    | types.UpdateEncryptedChatTyping
    | types.UpdateEncryption
    | types.UpdateEncryptedMessagesRead
    | types.UpdateChatParticipantAdd
    | types.UpdateChatParticipantDelete
    | types.UpdateDcOptions
    | types.UpdateNotifySettings
    | types.UpdateServiceNotification
    | types.UpdatePrivacy
    | types.UpdateUserPhone
    | types.UpdateReadHistoryInbox
    | types.UpdateReadHistoryOutbox
    | types.UpdateWebPage
    | types.UpdateReadMessagesContents
    | types.UpdateChannelTooLong
    | types.UpdateChannel
    | types.UpdateNewChannelMessage
    | types.UpdateReadChannelInbox
    | types.UpdateDeleteChannelMessages
    | types.UpdateChannelMessageViews
    | types.UpdateChatParticipantAdmin
    | types.UpdateNewStickerSet
    | types.UpdateStickerSetsOrder
    | types.UpdateStickerSets
    | types.UpdateSavedGifs
    | types.UpdateBotInlineQuery
    | types.UpdateBotInlineSend
    | types.UpdateEditChannelMessage
    | types.UpdateBotCallbackQuery
    | types.UpdateEditMessage
    | types.UpdateInlineBotCallbackQuery
    | types.UpdateReadChannelOutbox
    | types.UpdateDraftMessage
    | types.UpdateReadFeaturedStickers
    | types.UpdateRecentStickers
    | types.UpdateConfig
    | types.UpdatePtsChanged
    | types.UpdateChannelWebPage
    | types.UpdateDialogPinned
    | types.UpdatePinnedDialogs
    | types.UpdateBotWebhookJson
    | types.UpdateBotWebhookJsonquery
    | types.UpdateBotShippingQuery
    | types.UpdateBotPrecheckoutQuery
    | types.UpdatePhoneCall
    | types.UpdateLangPackTooLong
    | types.UpdateLangPack
    | types.UpdateFavedStickers
    | types.UpdateChannelReadMessagesContents
    | types.UpdateContactsReset
    | types.UpdateChannelAvailableMessages
    | types.UpdateDialogUnreadMark
    | types.UpdateMessagePoll
    | types.UpdateChatDefaultBannedRights
    | types.UpdateFolderPeers
    | types.UpdatePeerSettings
    | types.UpdatePeerLocated
    | types.UpdateNewScheduledMessage
    | types.UpdateDeleteScheduledMessages
    | types.UpdateTheme
    | types.UpdateGeoLiveViewed
    | types.UpdateLoginToken
    | types.UpdateMessagePollVote
    | types.UpdateDialogFilter
    | types.UpdateDialogFilterOrder
    | types.UpdateDialogFilters
    | types.UpdatePhoneCallSignalingData
    | types.UpdateChannelMessageForwards
    | types.UpdateReadChannelDiscussionInbox
    | types.UpdateReadChannelDiscussionOutbox
    | types.UpdatePeerBlocked
    | types.UpdateChannelUserTyping
    | types.UpdatePinnedMessages
    | types.UpdatePinnedChannelMessages
    | types.UpdateChat
    | types.UpdateGroupCallParticipants
    | types.UpdateGroupCall
    | types.UpdatePeerHistoryTtl
    | types.UpdateChatParticipant
    | types.UpdateChannelParticipant
    | types.UpdateBotStopped
    | types.UpdateGroupCallConnection
    | types.UpdateBotCommands
    | types.UpdatePendingJoinRequests
    | types.UpdateBotChatInviteRequester
    | types.UpdateMessageReactions
    | types.UpdateAttachMenuBots
    | types.UpdateWebViewResultSent
    | types.UpdateBotMenuButton
    | types.UpdateSavedRingtones
    | types.UpdateTranscribedAudio
    | types.UpdateReadFeaturedEmojiStickers
    | types.UpdateUserEmojiStatus
    | types.UpdateRecentEmojiStatuses
    | types.UpdateRecentReactions
    | types.UpdateMoveStickerSetToTop
    | types.UpdateMessageExtendedMedia
    | types.UpdateUser
    | types.UpdateAutoSaveSettings
    | types.UpdateStory
    | types.UpdateReadStories
    | types.UpdateStoryId
    | types.UpdateStoriesStealthMode
    | types.UpdateSentStoryReaction
    | types.UpdateBotChatBoost
    | types.UpdateChannelViewForumAsMessages
    | types.UpdatePeerWallpaper
    | types.UpdateBotMessageReaction
    | types.UpdateBotMessageReactions
    | types.UpdateSavedDialogPinned
    | types.UpdatePinnedSavedDialogs
    | types.UpdateSavedReactionTags
    | types.UpdateSmsJob
    | types.UpdateQuickReplies
    | types.UpdateNewQuickReply
    | types.UpdateDeleteQuickReply
    | types.UpdateQuickReplyMessage
    | types.UpdateDeleteQuickReplyMessages
    | types.UpdateBotBusinessConnect
    | types.UpdateBotNewBusinessMessage
    | types.UpdateBotEditBusinessMessage
    | types.UpdateBotDeleteBusinessMessage
    | types.UpdateNewStoryReaction
    | types.UpdateStarsBalance
    | types.UpdateBusinessBotCallbackQuery
    | types.UpdateStarsRevenueStatus
    | types.UpdateBotPurchasedPaidMedia
    | types.UpdatePaidReactionPrivacy
    | types.UpdateSentPhoneCode
    | types.UpdateGroupCallChainBlocks
    | types.UpdateReadMonoForumInbox
    | types.UpdateReadMonoForumOutbox
    | types.UpdateMonoForumNoPaidException
    | types.UpdateGroupCallMessage
    | types.UpdateGroupCallEncryptedMessage
    | types.UpdatePinnedForumTopic
    | types.UpdatePinnedForumTopics
    | types.UpdateDeleteGroupCallMessages
    | types.UpdateStarGiftAuctionState
    | types.UpdateStarGiftAuctionUserState
    | types.UpdateEmojiGameInfo
    | types.UpdateStarGiftCraftFail
    | types.UpdateChatParticipantRank
    | types.UpdateManagedBot
    | types.UpdateBotGuestChatQuery
    | types.UpdateAiComposeTones
)

Updates = (
    types.UpdatesTooLong
    | types.UpdateShortMessage
    | types.UpdateShortChatMessage
    | types.UpdateShort
    | types.UpdatesCombined
    | types.Updates
    | types.UpdateShortSentMessage
)

UrlAuthResult = (
    types.UrlAuthResultRequest
    | types.UrlAuthResultAccepted
    | types.UrlAuthResultDefault
)

User = types.UserEmpty | types.User

UserFull = types.UserFull

UserProfilePhoto = types.UserProfilePhotoEmpty | types.UserProfilePhoto

UserStatus = (
    types.UserStatusEmpty
    | types.UserStatusOnline
    | types.UserStatusOffline
    | types.UserStatusRecently
    | types.UserStatusLastWeek
    | types.UserStatusLastMonth
)

Username = types.Username

VideoSize = types.VideoSize | types.VideoSizeEmojiMarkup | types.VideoSizeStickerMarkup

WallPaper = types.WallPaper | types.WallPaperNoFile

WallPaperSettings = types.WallPaperSettings

WebAuthorization = types.WebAuthorization

WebDocument = types.WebDocument | types.WebDocumentNoProxy

WebPage = (
    types.WebPageEmpty | types.WebPagePending | types.WebPage | types.WebPageNotModified
)

WebPageAttribute = (
    types.WebPageAttributeTheme
    | types.WebPageAttributeStory
    | types.WebPageAttributeStickerSet
    | types.WebPageAttributeUniqueStarGift
    | types.WebPageAttributeStarGiftCollection
    | types.WebPageAttributeStarGiftAuction
    | types.WebPageAttributeAiComposeTone
)

WebViewMessageSent = types.WebViewMessageSent

WebViewResult = types.WebViewResultUrl
