"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

AuthorizationForm = types.account.AuthorizationForm

Authorizations = types.account.Authorizations

AutoDownloadSettings = types.account.AutoDownloadSettings

AutoSaveSettings = types.account.AutoSaveSettings

BusinessChatLinks = types.account.BusinessChatLinks

ChatThemes = types.account.ChatThemesNotModified | types.account.ChatThemes

ConnectedBots = types.account.ConnectedBots

ContentSettings = types.account.ContentSettings

EmailVerified = types.account.EmailVerified | types.account.EmailVerifiedLogin

EmojiStatuses = types.account.EmojiStatusesNotModified | types.account.EmojiStatuses

PaidMessagesRevenue = types.account.PaidMessagesRevenue

PasskeyRegistrationOptions = types.account.PasskeyRegistrationOptions

Passkeys = types.account.Passkeys

Password = types.account.Password

PasswordInputSettings = types.account.PasswordInputSettings

PasswordSettings = types.account.PasswordSettings

PrivacyRules = types.account.PrivacyRules

ResetPasswordResult = (
    types.account.ResetPasswordFailedWait
    | types.account.ResetPasswordRequestedWait
    | types.account.ResetPasswordOk
)

ResolvedBusinessChatLinks = types.account.ResolvedBusinessChatLinks

SavedMusicIds = types.account.SavedMusicIdsNotModified | types.account.SavedMusicIds

SavedRingtone = types.account.SavedRingtone | types.account.SavedRingtoneConverted

SavedRingtones = types.account.SavedRingtonesNotModified | types.account.SavedRingtones

SentEmailCode = types.account.SentEmailCode

Takeout = types.account.Takeout

Themes = types.account.ThemesNotModified | types.account.Themes

TmpPassword = types.account.TmpPassword

WallPapers = types.account.WallPapersNotModified | types.account.WallPapers

WebAuthorizations = types.account.WebAuthorizations
