"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

Authorization = types.auth.Authorization | types.auth.AuthorizationSignUpRequired

CodeType = (
    types.auth.CodeTypeSms
    | types.auth.CodeTypeCall
    | types.auth.CodeTypeFlashCall
    | types.auth.CodeTypeMissedCall
    | types.auth.CodeTypeFragmentSms
)

ExportedAuthorization = types.auth.ExportedAuthorization

LoggedOut = types.auth.LoggedOut

LoginToken = (
    types.auth.LoginToken
    | types.auth.LoginTokenMigrateTo
    | types.auth.LoginTokenSuccess
)

PasskeyLoginOptions = types.auth.PasskeyLoginOptions

PasswordRecovery = types.auth.PasswordRecovery

SentCode = (
    types.auth.SentCode
    | types.auth.SentCodeSuccess
    | types.auth.SentCodePaymentRequired
)

SentCodeType = (
    types.auth.SentCodeTypeApp
    | types.auth.SentCodeTypeSms
    | types.auth.SentCodeTypeCall
    | types.auth.SentCodeTypeFlashCall
    | types.auth.SentCodeTypeMissedCall
    | types.auth.SentCodeTypeEmailCode
    | types.auth.SentCodeTypeSetUpEmailRequired
    | types.auth.SentCodeTypeFragmentSms
    | types.auth.SentCodeTypeFirebaseSms
    | types.auth.SentCodeTypeSmsWord
    | types.auth.SentCodeTypeSmsPhrase
)
