"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

AccessSettings = types.bots.AccessSettings

BotInfo = types.bots.BotInfo

ExportedBotToken = types.bots.ExportedBotToken

PopularAppBots = types.bots.PopularAppBots

PreviewInfo = types.bots.PreviewInfo

RequestedButton = types.bots.RequestedButton
