"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

AdminLogResults = types.channels.AdminLogResults

ChannelParticipant = types.channels.ChannelParticipant

ChannelParticipants = (
    types.channels.ChannelParticipants | types.channels.ChannelParticipantsNotModified
)

SendAsPeers = types.channels.SendAsPeers

SponsoredMessageReportResult = (
    types.channels.SponsoredMessageReportResultChooseOption
    | types.channels.SponsoredMessageReportResultAdsHidden
    | types.channels.SponsoredMessageReportResultReported
)
