"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

ChatlistInvite = types.chatlists.ChatlistInviteAlready | types.chatlists.ChatlistInvite

ChatlistUpdates = types.chatlists.ChatlistUpdates

ExportedChatlistInvite = types.chatlists.ExportedChatlistInvite

ExportedInvites = types.chatlists.ExportedInvites
