"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

Blocked = types.contacts.Blocked | types.contacts.BlockedSlice

ContactBirthdays = types.contacts.ContactBirthdays

Contacts = types.contacts.ContactsNotModified | types.contacts.Contacts

Found = types.contacts.Found

ImportedContacts = types.contacts.ImportedContacts

ResolvedPeer = types.contacts.ResolvedPeer

SponsoredPeers = types.contacts.SponsoredPeersEmpty | types.contacts.SponsoredPeers

TopPeers = (
    types.contacts.TopPeersNotModified
    | types.contacts.TopPeers
    | types.contacts.TopPeersDisabled
)
