"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

AppConfig = types.help.AppConfigNotModified | types.help.AppConfig

AppUpdate = types.help.AppUpdate | types.help.NoAppUpdate

ConfigSimple = types.help.ConfigSimple

CountriesList = types.help.CountriesListNotModified | types.help.CountriesList

Country = types.help.Country

CountryCode = types.help.CountryCode

DeepLinkInfo = types.help.DeepLinkInfoEmpty | types.help.DeepLinkInfo

InviteText = types.help.InviteText

PassportConfig = types.help.PassportConfigNotModified | types.help.PassportConfig

PeerColorOption = types.help.PeerColorOption

PeerColorSet = types.help.PeerColorSet | types.help.PeerColorProfileSet

PeerColors = types.help.PeerColorsNotModified | types.help.PeerColors

PremiumPromo = types.help.PremiumPromo

PromoData = types.help.PromoDataEmpty | types.help.PromoData

RecentMeUrls = types.help.RecentMeUrls

Support = types.help.Support

SupportName = types.help.SupportName

TermsOfService = types.help.TermsOfService

TermsOfServiceUpdate = (
    types.help.TermsOfServiceUpdateEmpty | types.help.TermsOfServiceUpdate
)

TimezonesList = types.help.TimezonesListNotModified | types.help.TimezonesList

UserInfo = types.help.UserInfoEmpty | types.help.UserInfo
