"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

AffectedFoundMessages = types.messages.AffectedFoundMessages

AffectedHistory = types.messages.AffectedHistory

AffectedMessages = types.messages.AffectedMessages

AllStickers = types.messages.AllStickersNotModified | types.messages.AllStickers

ArchivedStickers = types.messages.ArchivedStickers

AvailableEffects = (
    types.messages.AvailableEffectsNotModified | types.messages.AvailableEffects
)

AvailableReactions = (
    types.messages.AvailableReactionsNotModified | types.messages.AvailableReactions
)

BotApp = types.messages.BotApp

BotCallbackAnswer = types.messages.BotCallbackAnswer

BotPreparedInlineMessage = types.messages.BotPreparedInlineMessage

BotResults = types.messages.BotResults

ChatAdminsWithInvites = types.messages.ChatAdminsWithInvites

ChatFull = types.messages.ChatFull

ChatInviteImporters = types.messages.ChatInviteImporters

Chats = types.messages.Chats | types.messages.ChatsSlice

CheckedHistoryImportPeer = types.messages.CheckedHistoryImportPeer

ComposedMessageWithAi = types.messages.ComposedMessageWithAi

DhConfig = types.messages.DhConfigNotModified | types.messages.DhConfig

DialogFilters = types.messages.DialogFilters

Dialogs = (
    types.messages.Dialogs
    | types.messages.DialogsSlice
    | types.messages.DialogsNotModified
)

DiscussionMessage = types.messages.DiscussionMessage

EmojiGameInfo = types.messages.EmojiGameUnavailable | types.messages.EmojiGameDiceInfo

EmojiGameOutcome = types.messages.EmojiGameOutcome

EmojiGroups = types.messages.EmojiGroupsNotModified | types.messages.EmojiGroups

ExportedChatInvite = (
    types.messages.ExportedChatInvite | types.messages.ExportedChatInviteReplaced
)

ExportedChatInvites = types.messages.ExportedChatInvites

FavedStickers = types.messages.FavedStickersNotModified | types.messages.FavedStickers

FeaturedStickers = (
    types.messages.FeaturedStickersNotModified | types.messages.FeaturedStickers
)

ForumTopics = types.messages.ForumTopics

FoundStickerSets = (
    types.messages.FoundStickerSetsNotModified | types.messages.FoundStickerSets
)

FoundStickers = types.messages.FoundStickersNotModified | types.messages.FoundStickers

HighScores = types.messages.HighScores

HistoryImport = types.messages.HistoryImport

HistoryImportParsed = types.messages.HistoryImportParsed

InactiveChats = types.messages.InactiveChats

InvitedUsers = types.messages.InvitedUsers

MessageEditData = types.messages.MessageEditData

MessageReactionsList = types.messages.MessageReactionsList

MessageViews = types.messages.MessageViews

Messages = (
    types.messages.Messages
    | types.messages.MessagesSlice
    | types.messages.ChannelMessages
    | types.messages.MessagesNotModified
)

MyStickers = types.messages.MyStickers

PeerDialogs = types.messages.PeerDialogs

PeerSettings = types.messages.PeerSettings

PreparedInlineMessage = types.messages.PreparedInlineMessage

QuickReplies = types.messages.QuickReplies | types.messages.QuickRepliesNotModified

Reactions = types.messages.ReactionsNotModified | types.messages.Reactions

RecentStickers = (
    types.messages.RecentStickersNotModified | types.messages.RecentStickers
)

SavedDialogs = (
    types.messages.SavedDialogs
    | types.messages.SavedDialogsSlice
    | types.messages.SavedDialogsNotModified
)

SavedGifs = types.messages.SavedGifsNotModified | types.messages.SavedGifs

SavedReactionTags = (
    types.messages.SavedReactionTagsNotModified | types.messages.SavedReactionTags
)

SearchCounter = types.messages.SearchCounter

SearchResultsCalendar = types.messages.SearchResultsCalendar

SearchResultsPositions = types.messages.SearchResultsPositions

SentEncryptedMessage = (
    types.messages.SentEncryptedMessage | types.messages.SentEncryptedFile
)

SponsoredMessages = (
    types.messages.SponsoredMessages | types.messages.SponsoredMessagesEmpty
)

StickerSet = types.messages.StickerSet | types.messages.StickerSetNotModified

StickerSetInstallResult = (
    types.messages.StickerSetInstallResultSuccess
    | types.messages.StickerSetInstallResultArchive
)

Stickers = types.messages.StickersNotModified | types.messages.Stickers

TranscribedAudio = types.messages.TranscribedAudio

TranslatedText = types.messages.TranslateResult

VotesList = types.messages.VotesList

WebPage = types.messages.WebPage

WebPagePreview = types.messages.WebPagePreview
