"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

BankCardData = types.payments.BankCardData

CheckCanSendGiftResult = (
    types.payments.CheckCanSendGiftResultOk | types.payments.CheckCanSendGiftResultFail
)

CheckedGiftCode = types.payments.CheckedGiftCode

ConnectedStarRefBots = types.payments.ConnectedStarRefBots

ExportedInvoice = types.payments.ExportedInvoice

GiveawayInfo = types.payments.GiveawayInfo | types.payments.GiveawayInfoResults

PaymentForm = (
    types.payments.PaymentForm
    | types.payments.PaymentFormStars
    | types.payments.PaymentFormStarGift
)

PaymentReceipt = types.payments.PaymentReceipt | types.payments.PaymentReceiptStars

PaymentResult = types.payments.PaymentResult | types.payments.PaymentVerificationNeeded

ResaleStarGifts = types.payments.ResaleStarGifts

SavedInfo = types.payments.SavedInfo

SavedStarGifts = types.payments.SavedStarGifts

StarGiftActiveAuctions = (
    types.payments.StarGiftActiveAuctionsNotModified
    | types.payments.StarGiftActiveAuctions
)

StarGiftAuctionAcquiredGifts = types.payments.StarGiftAuctionAcquiredGifts

StarGiftAuctionState = types.payments.StarGiftAuctionState

StarGiftCollections = (
    types.payments.StarGiftCollectionsNotModified | types.payments.StarGiftCollections
)

StarGiftUpgradeAttributes = types.payments.StarGiftUpgradeAttributes

StarGiftUpgradePreview = types.payments.StarGiftUpgradePreview

StarGiftWithdrawalUrl = types.payments.StarGiftWithdrawalUrl

StarGifts = types.payments.StarGiftsNotModified | types.payments.StarGifts

StarsRevenueAdsAccountUrl = types.payments.StarsRevenueAdsAccountUrl

StarsRevenueStats = types.payments.StarsRevenueStats

StarsRevenueWithdrawalUrl = types.payments.StarsRevenueWithdrawalUrl

StarsStatus = types.payments.StarsStatus

SuggestedStarRefBots = types.payments.SuggestedStarRefBots

UniqueStarGift = types.payments.UniqueStarGift

UniqueStarGiftValueInfo = types.payments.UniqueStarGiftValueInfo

ValidatedRequestedInfo = types.payments.ValidatedRequestedInfo
