"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

ExportedGroupCallInvite = types.phone.ExportedGroupCallInvite

GroupCall = types.phone.GroupCall

GroupCallStars = types.phone.GroupCallStars

GroupCallStreamChannels = types.phone.GroupCallStreamChannels

GroupCallStreamRtmpUrl = types.phone.GroupCallStreamRtmpUrl

GroupParticipants = types.phone.GroupParticipants

JoinAsPeers = types.phone.JoinAsPeers

PhoneCall = types.phone.PhoneCall
