"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

BoostsList = types.premium.BoostsList

BoostsStatus = types.premium.BoostsStatus

MyBoosts = types.premium.MyBoosts
