"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

BroadcastStats = types.stats.BroadcastStats

MegagroupStats = types.stats.MegagroupStats

MessageStats = types.stats.MessageStats

PollStats = types.stats.PollStats

PublicForwards = types.stats.PublicForwards

StoryStats = types.stats.StoryStats
