"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

Albums = types.stories.AlbumsNotModified | types.stories.Albums

AllStories = types.stories.AllStoriesNotModified | types.stories.AllStories

CanSendStoryCount = types.stories.CanSendStoryCount

FoundStories = types.stories.FoundStories

PeerStories = types.stories.PeerStories

Stories = types.stories.Stories

StoryReactionsList = types.stories.StoryReactionsList

StoryViews = types.stories.StoryViews

StoryViewsList = types.stories.StoryViewsList
