"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

FileType = (
    types.storage.FileUnknown
    | types.storage.FilePartial
    | types.storage.FileJpeg
    | types.storage.FileGif
    | types.storage.FilePng
    | types.storage.FilePdf
    | types.storage.FileMp3
    | types.storage.FileMov
    | types.storage.FileMp4
    | types.storage.FileWebp
)
