"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

ChannelDifference = (
    types.updates.ChannelDifferenceEmpty
    | types.updates.ChannelDifferenceTooLong
    | types.updates.ChannelDifference
)

Difference = (
    types.updates.DifferenceEmpty
    | types.updates.Difference
    | types.updates.DifferenceSlice
    | types.updates.DifferenceTooLong
)

State = types.updates.State
