"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

CdnFile = types.upload.CdnFileReuploadNeeded | types.upload.CdnFile

File = types.upload.File | types.upload.FileCdnRedirect

WebFile = types.upload.WebFile
