"""File generated by TLObjects' generator. All changes will be ERASED"""

from grammers.tl import types

SavedMusic = types.users.SavedMusicNotModified | types.users.SavedMusic

UserFull = types.users.UserFull

Users = types.users.Users | types.users.UsersSlice
