from grammers.tl import types
from typing import final, Self, Sequence

@final
class PeerId:
    def __new__(cls, id: PeerIdLike) -> Self: ...
    @staticmethod
    def self_user() -> Self: ...
    @staticmethod
    def user(id: int) -> Self: ...
    @staticmethod
    def chat(id: int) -> Self: ...
    @staticmethod
    def channel(id: int) -> Self: ...
    @property
    def kind(self) -> PeerKind:
        """
        Peer kind.
        """
        ...
    @property
    def bot_api_dialog_id(self) -> int:
        """
        Returns the identity using the Bot API Dialog ID format.

        Will return an arbitrary value if [`self.kind`] is [`PeerKind.UserSelf`].
        This value should not be relied on and may change between releases.
        """
        ...
    @property
    def bare_id(self) -> int:
        """
        Unpacked peer identifier. Panics if [`self.kind`] is [`PeerKind.UserSelf`].
        """
        ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self) -> bool: ...
    def __hash__(self) -> int: ...

PeerIdLike = int | PeerId | types.InputPeer | types.Peer

@final
class PeerKind:
    """The peer identity belongs to a [`tl.types.User`]. May also represent [`PeerKind.UserSelf`]."""

    User = 0
    """The peer identity belongs to a user with its [`tl.types.User.is_self`] flag set to `true`."""
    UserSelf = 1
    """The peer identity belongs to a [`tl.types.Chat`] or one of its derivatives."""
    Chat = 2
    """The peer identity belongs to a [`tl.types.Channel`] or one of its derivatives."""
    Channel = 3

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self) -> bool: ...
    def __hash__(self) -> int: ...

@final
class PeerAuth:
    def __new__(cls, access_hash: int) -> Self: ...
    @property
    def hash(self) -> int: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ChannelKind:
    """Value used for a channel with its [`tl.types.Channel.broadcast`] flag set to `true`."""

    Broadcast = 1
    """Value used for a channel with its [`tl.types.Channel.megagroup`] flag set to `true`."""
    Megagroup = 2
    """Value used for a channel with its [`tl.types.Channel.gigagroup`] flag set to `true`."""
    Gigagroup = 3

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self) -> bool: ...
    def __hash__(self) -> int: ...

@final
class PeerInfo:
    class User: ...

    @staticmethod
    def user(
        id: int,
        auth: int | PeerAuth | None,
        bot: bool | None,
        is_self: bool | None,
    ) -> Self: ...
    @staticmethod
    def chat(id: int) -> Self: ...
    @staticmethod
    def channel(
        id: int,
        auth: int | PeerAuth | None,
        kind: ChannelKind | None,
    ) -> Self: ...
    @property
    def id(self) -> PeerId: ...
    @property
    def bot_api_dialog_id(self) -> int: ...
    @property
    def auth(self) -> PeerAuth: ...
    def __repr__(self) -> str: ...
    def __eq__(self) -> bool: ...

@final
class DcOption:
    def __new__(
        cls,
        id: int,
        ipv4: str | None,
        ipv6: str | None,
        auth_key: bytes | None,
    ) -> Self: ...
    @property
    def id(self) -> int: ...
    @id.setter
    def id(self, id: int) -> None: ...
    @property
    def ipv4(self) -> SocketAddrV4: ...
    @ipv4.setter
    def ipv4(self, ipv4: SocketAddrV4) -> None: ...
    @property
    def ipv6(self) -> SocketAddrV6: ...
    @ipv6.setter
    def ipv6(self, ipv6: SocketAddrV6) -> None: ...
    @property
    def auth_key(self) -> bytes: ...
    @auth_key.setter
    def auth_key(self, auth_key: bytes) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self) -> bool: ...

@final
class SocketAddrV4:
    def __new__(cls, ip: str | Sequence[int], port: int) -> Self: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, a: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, b: int) -> None: ...
    @property
    def c(self) -> int: ...
    @c.setter
    def c(self, c: int) -> None: ...
    @property
    def d(self) -> int: ...
    @d.setter
    def d(self, d: int) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, port: int) -> None: ...
    @property
    def ip(self) -> int: ...
    @ip.setter
    def ip(self, ip: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self) -> bool: ...

@final
class SocketAddrV6:
    def __new__(cls, ip: str | Sequence[int], port: int) -> Self: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, a: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, b: int) -> None: ...
    @property
    def c(self) -> int: ...
    @c.setter
    def c(self, c: int) -> None: ...
    @property
    def d(self) -> int: ...
    @d.setter
    def d(self, d: int) -> None: ...
    @property
    def e(self) -> int: ...
    @e.setter
    def e(self, e: int) -> None: ...
    @property
    def f(self) -> int: ...
    @f.setter
    def f(self, f: int) -> None: ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, g: int) -> None: ...
    @property
    def h(self) -> int: ...
    @h.setter
    def h(self, h: int) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, port: int) -> None: ...
    @property
    def ip(self) -> int: ...
    @ip.setter
    def ip(self, ip: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self) -> bool: ...

@final
class ChannelState:
    def __new__(cls, id: int, pts: int) -> Self: ...
    def __repr__(self) -> str: ...
    def __eq__(self) -> bool: ...

@final
class UpdatesState(UpdateState):
    def __new__(
        cls,
        pts: int | UpdateState | UpdatesState,
        qts: int,
        date: int,
        seq: int,
        channels: Sequence[ChannelState],
    ) -> Self: ...
    def __repr__(self) -> str: ...
    def __eq__(self) -> bool: ...

class UpdateState:
    All = UpdatesState
    class Primary:
        def __new__(cls, pts: int, date: int, seq: int) -> Self: ...
        def __repr__(self) -> str: ...
        def __eq__(self) -> bool: ...

    class Secondary:
        def __new__(cls, qts: int) -> Self: ...
        def __repr__(self) -> str: ...
        def __eq__(self) -> bool: ...

    class Channel:
        def __new__(cls, id: int, pts: int) -> Self: ...
        def __repr__(self) -> str: ...
        def __eq__(self) -> bool: ...

    def __repr__(self) -> str: ...
    def __eq__(self) -> bool: ...
