"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class ChangePhone(TLObject, TLRequest):
    """
    [Read `account.changePhone` docs](https://core.telegram.org/method/account.changePhone).

    Generated from the following TL definition:
    ```tl
    account.changePhone#70c32edb phone_number:string phone_code_hash:string phone_code:string = User
    ```
    """
    def __new__(
        cls,
        phone_number: str,
        phone_code_hash: str,
        phone_code: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class CreateBusinessChatLink(TLObject, TLRequest):
    """
    [Read `account.createBusinessChatLink` docs](https://core.telegram.org/method/account.createBusinessChatLink).

    Generated from the following TL definition:
    ```tl
    account.createBusinessChatLink#8851e68e link:InputBusinessChatLink = BusinessChatLink
    ```
    """
    def __new__(
        cls,
        link: types.InputBusinessChatLink,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class CreateTheme(TLObject, TLRequest):
    """
    [Read `account.createTheme` docs](https://core.telegram.org/method/account.createTheme).

    Generated from the following TL definition:
    ```tl
    account.createTheme#652e4400 flags:# slug:string title:string document:flags.2?InputDocument settings:flags.3?Vector<InputThemeSettings> = Theme
    ```
    """
    def __new__(
        cls,
        slug: str,
        title: str,
        document: Optional[types.InputDocumentEmpty | types.InputDocument],
        settings: Optional[Sequence[types.InputThemeSettings]],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class EditBusinessChatLink(TLObject, TLRequest):
    """
    [Read `account.editBusinessChatLink` docs](https://core.telegram.org/method/account.editBusinessChatLink).

    Generated from the following TL definition:
    ```tl
    account.editBusinessChatLink#8c3410af slug:string link:InputBusinessChatLink = BusinessChatLink
    ```
    """
    def __new__(
        cls,
        slug: str,
        link: types.InputBusinessChatLink,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAccountTtl(TLObject, TLRequest):
    """
    [Read `account.getAccountTTL` docs](https://core.telegram.org/method/account.getAccountTTL).

    Generated from the following TL definition:
    ```tl
    account.getAccountTTL#8fc711d = AccountDaysTTL
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAllSecureValues(TLObject, TLRequest):
    """
    [Read `account.getAllSecureValues` docs](https://core.telegram.org/method/account.getAllSecureValues).

    Generated from the following TL definition:
    ```tl
    account.getAllSecureValues#b288bc7d = Vector<SecureValue>
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAuthorizationForm(TLObject, TLRequest):
    """
    [Read `account.getAuthorizationForm` docs](https://core.telegram.org/method/account.getAuthorizationForm).

    Generated from the following TL definition:
    ```tl
    account.getAuthorizationForm#a929597a bot_id:long scope:string public_key:string = account.AuthorizationForm
    ```
    """
    def __new__(
        cls,
        bot_id: int,
        scope: str,
        public_key: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAuthorizations(TLObject, TLRequest):
    """
    [Read `account.getAuthorizations` docs](https://core.telegram.org/method/account.getAuthorizations).

    Generated from the following TL definition:
    ```tl
    account.getAuthorizations#e320c158 = account.Authorizations
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAutoDownloadSettings(TLObject, TLRequest):
    """
    [Read `account.getAutoDownloadSettings` docs](https://core.telegram.org/method/account.getAutoDownloadSettings).

    Generated from the following TL definition:
    ```tl
    account.getAutoDownloadSettings#56da0b3f = account.AutoDownloadSettings
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAutoSaveSettings(TLObject, TLRequest):
    """
    [Read `account.getAutoSaveSettings` docs](https://core.telegram.org/method/account.getAutoSaveSettings).

    Generated from the following TL definition:
    ```tl
    account.getAutoSaveSettings#adcbbcda = account.AutoSaveSettings
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetBotBusinessConnection(TLObject, TLRequest):
    """
    [Read `account.getBotBusinessConnection` docs](https://core.telegram.org/method/account.getBotBusinessConnection).

    Generated from the following TL definition:
    ```tl
    account.getBotBusinessConnection#76a86270 connection_id:string = Updates
    ```
    """
    def __new__(
        cls,
        connection_id: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetBusinessChatLinks(TLObject, TLRequest):
    """
    [Read `account.getBusinessChatLinks` docs](https://core.telegram.org/method/account.getBusinessChatLinks).

    Generated from the following TL definition:
    ```tl
    account.getBusinessChatLinks#6f70dde1 = account.BusinessChatLinks
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetChannelDefaultEmojiStatuses(TLObject, TLRequest):
    """
    [Read `account.getChannelDefaultEmojiStatuses` docs](https://core.telegram.org/method/account.getChannelDefaultEmojiStatuses).

    Generated from the following TL definition:
    ```tl
    account.getChannelDefaultEmojiStatuses#7727a7d5 hash:long = account.EmojiStatuses
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetChannelRestrictedStatusEmojis(TLObject, TLRequest):
    """
    [Read `account.getChannelRestrictedStatusEmojis` docs](https://core.telegram.org/method/account.getChannelRestrictedStatusEmojis).

    Generated from the following TL definition:
    ```tl
    account.getChannelRestrictedStatusEmojis#35a9e0d5 hash:long = EmojiList
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetChatThemes(TLObject, TLRequest):
    """
    [Read `account.getChatThemes` docs](https://core.telegram.org/method/account.getChatThemes).

    Generated from the following TL definition:
    ```tl
    account.getChatThemes#d638de89 hash:long = account.Themes
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetCollectibleEmojiStatuses(TLObject, TLRequest):
    """
    [Read `account.getCollectibleEmojiStatuses` docs](https://core.telegram.org/method/account.getCollectibleEmojiStatuses).

    Generated from the following TL definition:
    ```tl
    account.getCollectibleEmojiStatuses#2e7b4543 hash:long = account.EmojiStatuses
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetConnectedBots(TLObject, TLRequest):
    """
    [Read `account.getConnectedBots` docs](https://core.telegram.org/method/account.getConnectedBots).

    Generated from the following TL definition:
    ```tl
    account.getConnectedBots#4ea4c80f = account.ConnectedBots
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetContentSettings(TLObject, TLRequest):
    """
    [Read `account.getContentSettings` docs](https://core.telegram.org/method/account.getContentSettings).

    Generated from the following TL definition:
    ```tl
    account.getContentSettings#8b9b4dae = account.ContentSettings
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetDefaultBackgroundEmojis(TLObject, TLRequest):
    """
    [Read `account.getDefaultBackgroundEmojis` docs](https://core.telegram.org/method/account.getDefaultBackgroundEmojis).

    Generated from the following TL definition:
    ```tl
    account.getDefaultBackgroundEmojis#a60ab9ce hash:long = EmojiList
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetDefaultEmojiStatuses(TLObject, TLRequest):
    """
    [Read `account.getDefaultEmojiStatuses` docs](https://core.telegram.org/method/account.getDefaultEmojiStatuses).

    Generated from the following TL definition:
    ```tl
    account.getDefaultEmojiStatuses#d6753386 hash:long = account.EmojiStatuses
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetDefaultGroupPhotoEmojis(TLObject, TLRequest):
    """
    [Read `account.getDefaultGroupPhotoEmojis` docs](https://core.telegram.org/method/account.getDefaultGroupPhotoEmojis).

    Generated from the following TL definition:
    ```tl
    account.getDefaultGroupPhotoEmojis#915860ae hash:long = EmojiList
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetDefaultProfilePhotoEmojis(TLObject, TLRequest):
    """
    [Read `account.getDefaultProfilePhotoEmojis` docs](https://core.telegram.org/method/account.getDefaultProfilePhotoEmojis).

    Generated from the following TL definition:
    ```tl
    account.getDefaultProfilePhotoEmojis#e2750328 hash:long = EmojiList
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetGlobalPrivacySettings(TLObject, TLRequest):
    """
    [Read `account.getGlobalPrivacySettings` docs](https://core.telegram.org/method/account.getGlobalPrivacySettings).

    Generated from the following TL definition:
    ```tl
    account.getGlobalPrivacySettings#eb2b4cf6 = GlobalPrivacySettings
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetMultiWallPapers(TLObject, TLRequest):
    """
    [Read `account.getMultiWallPapers` docs](https://core.telegram.org/method/account.getMultiWallPapers).

    Generated from the following TL definition:
    ```tl
    account.getMultiWallPapers#65ad71dc wallpapers:Vector<InputWallPaper> = Vector<WallPaper>
    ```
    """
    def __new__(
        cls,
        wallpapers: Sequence[
            types.InputWallPaper | types.InputWallPaperSlug | types.InputWallPaperNoFile
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetNotifyExceptions(TLObject, TLRequest):
    """
    [Read `account.getNotifyExceptions` docs](https://core.telegram.org/method/account.getNotifyExceptions).

    Generated from the following TL definition:
    ```tl
    account.getNotifyExceptions#53577479 flags:# compare_sound:flags.1?true compare_stories:flags.2?true peer:flags.0?InputNotifyPeer = Updates
    ```
    """
    def __new__(
        cls,
        compare_sound: bool,
        compare_stories: bool,
        peer: Optional[
            types.InputNotifyPeer
            | types.InputNotifyUsers
            | types.InputNotifyChats
            | types.InputNotifyBroadcasts
            | types.InputNotifyForumTopic
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetNotifySettings(TLObject, TLRequest):
    """
    [Read `account.getNotifySettings` docs](https://core.telegram.org/method/account.getNotifySettings).

    Generated from the following TL definition:
    ```tl
    account.getNotifySettings#12b3ad31 peer:InputNotifyPeer = PeerNotifySettings
    ```
    """
    def __new__(
        cls,
        peer: types.InputNotifyPeer
        | types.InputNotifyUsers
        | types.InputNotifyChats
        | types.InputNotifyBroadcasts
        | types.InputNotifyForumTopic,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPaidMessagesRevenue(TLObject, TLRequest):
    """
    [Read `account.getPaidMessagesRevenue` docs](https://core.telegram.org/method/account.getPaidMessagesRevenue).

    Generated from the following TL definition:
    ```tl
    account.getPaidMessagesRevenue#19ba4a67 flags:# parent_peer:flags.0?InputPeer user_id:InputUser = account.PaidMessagesRevenue
    ```
    """
    def __new__(
        cls,
        parent_peer: Optional[
            types.InputPeerEmpty
            | types.InputPeerSelf
            | types.InputPeerChat
            | types.InputPeerUser
            | types.InputPeerChannel
            | types.InputPeerUserFromMessage
            | types.InputPeerChannelFromMessage
        ],
        user_id: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPasskeys(TLObject, TLRequest):
    """
    [Read `account.getPasskeys` docs](https://core.telegram.org/method/account.getPasskeys).

    Generated from the following TL definition:
    ```tl
    account.getPasskeys#ea1f0c52 = account.Passkeys
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPassword(TLObject, TLRequest):
    """
    [Read `account.getPassword` docs](https://core.telegram.org/method/account.getPassword).

    Generated from the following TL definition:
    ```tl
    account.getPassword#548a30f5 = account.Password
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPasswordSettings(TLObject, TLRequest):
    """
    [Read `account.getPasswordSettings` docs](https://core.telegram.org/method/account.getPasswordSettings).

    Generated from the following TL definition:
    ```tl
    account.getPasswordSettings#9cd4eaf9 password:InputCheckPasswordSRP = account.PasswordSettings
    ```
    """
    def __new__(
        cls,
        password: types.InputCheckPasswordEmpty | types.InputCheckPasswordSrp,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPrivacy(TLObject, TLRequest):
    """
    [Read `account.getPrivacy` docs](https://core.telegram.org/method/account.getPrivacy).

    Generated from the following TL definition:
    ```tl
    account.getPrivacy#dadbc950 key:InputPrivacyKey = account.PrivacyRules
    ```
    """
    def __new__(
        cls,
        key: types.InputPrivacyKeyStatusTimestamp
        | types.InputPrivacyKeyChatInvite
        | types.InputPrivacyKeyPhoneCall
        | types.InputPrivacyKeyPhoneP2P
        | types.InputPrivacyKeyForwards
        | types.InputPrivacyKeyProfilePhoto
        | types.InputPrivacyKeyPhoneNumber
        | types.InputPrivacyKeyAddedByPhone
        | types.InputPrivacyKeyVoiceMessages
        | types.InputPrivacyKeyAbout
        | types.InputPrivacyKeyBirthday
        | types.InputPrivacyKeyStarGiftsAutoSave
        | types.InputPrivacyKeyNoPaidMessages
        | types.InputPrivacyKeySavedMusic,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetReactionsNotifySettings(TLObject, TLRequest):
    """
    [Read `account.getReactionsNotifySettings` docs](https://core.telegram.org/method/account.getReactionsNotifySettings).

    Generated from the following TL definition:
    ```tl
    account.getReactionsNotifySettings#6dd654c = ReactionsNotifySettings
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetRecentEmojiStatuses(TLObject, TLRequest):
    """
    [Read `account.getRecentEmojiStatuses` docs](https://core.telegram.org/method/account.getRecentEmojiStatuses).

    Generated from the following TL definition:
    ```tl
    account.getRecentEmojiStatuses#f578105 hash:long = account.EmojiStatuses
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetSavedMusicIds(TLObject, TLRequest):
    """
    [Read `account.getSavedMusicIds` docs](https://core.telegram.org/method/account.getSavedMusicIds).

    Generated from the following TL definition:
    ```tl
    account.getSavedMusicIds#e09d5faf hash:long = account.SavedMusicIds
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetSavedRingtones(TLObject, TLRequest):
    """
    [Read `account.getSavedRingtones` docs](https://core.telegram.org/method/account.getSavedRingtones).

    Generated from the following TL definition:
    ```tl
    account.getSavedRingtones#e1902288 hash:long = account.SavedRingtones
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetSecureValue(TLObject, TLRequest):
    """
    [Read `account.getSecureValue` docs](https://core.telegram.org/method/account.getSecureValue).

    Generated from the following TL definition:
    ```tl
    account.getSecureValue#73665bc2 types:Vector<SecureValueType> = Vector<SecureValue>
    ```
    """
    def __new__(
        cls,
        types: Sequence[
            types.SecureValueTypePersonalDetails
            | types.SecureValueTypePassport
            | types.SecureValueTypeDriverLicense
            | types.SecureValueTypeIdentityCard
            | types.SecureValueTypeInternalPassport
            | types.SecureValueTypeAddress
            | types.SecureValueTypeUtilityBill
            | types.SecureValueTypeBankStatement
            | types.SecureValueTypeRentalAgreement
            | types.SecureValueTypePassportRegistration
            | types.SecureValueTypeTemporaryRegistration
            | types.SecureValueTypePhone
            | types.SecureValueTypeEmail
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetTheme(TLObject, TLRequest):
    """
    [Read `account.getTheme` docs](https://core.telegram.org/method/account.getTheme).

    Generated from the following TL definition:
    ```tl
    account.getTheme#3a5869ec format:string theme:InputTheme = Theme
    ```
    """
    def __new__(
        cls,
        format: str,
        theme: types.InputTheme | types.InputThemeSlug,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetThemes(TLObject, TLRequest):
    """
    [Read `account.getThemes` docs](https://core.telegram.org/method/account.getThemes).

    Generated from the following TL definition:
    ```tl
    account.getThemes#7206e458 format:string hash:long = account.Themes
    ```
    """
    def __new__(
        cls,
        format: str,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetTmpPassword(TLObject, TLRequest):
    """
    [Read `account.getTmpPassword` docs](https://core.telegram.org/method/account.getTmpPassword).

    Generated from the following TL definition:
    ```tl
    account.getTmpPassword#449e0b51 password:InputCheckPasswordSRP period:int = account.TmpPassword
    ```
    """
    def __new__(
        cls,
        password: types.InputCheckPasswordEmpty | types.InputCheckPasswordSrp,
        period: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetUniqueGiftChatThemes(TLObject, TLRequest):
    """
    [Read `account.getUniqueGiftChatThemes` docs](https://core.telegram.org/method/account.getUniqueGiftChatThemes).

    Generated from the following TL definition:
    ```tl
    account.getUniqueGiftChatThemes#e42ce9c9 offset:string limit:int hash:long = account.ChatThemes
    ```
    """
    def __new__(
        cls,
        offset: str,
        limit: int,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetWallPaper(TLObject, TLRequest):
    """
    [Read `account.getWallPaper` docs](https://core.telegram.org/method/account.getWallPaper).

    Generated from the following TL definition:
    ```tl
    account.getWallPaper#fc8ddbea wallpaper:InputWallPaper = WallPaper
    ```
    """
    def __new__(
        cls,
        wallpaper: types.InputWallPaper
        | types.InputWallPaperSlug
        | types.InputWallPaperNoFile,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetWallPapers(TLObject, TLRequest):
    """
    [Read `account.getWallPapers` docs](https://core.telegram.org/method/account.getWallPapers).

    Generated from the following TL definition:
    ```tl
    account.getWallPapers#7967d36 hash:long = account.WallPapers
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetWebAuthorizations(TLObject, TLRequest):
    """
    [Read `account.getWebAuthorizations` docs](https://core.telegram.org/method/account.getWebAuthorizations).

    Generated from the following TL definition:
    ```tl
    account.getWebAuthorizations#182e6d6f = account.WebAuthorizations
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class InitPasskeyRegistration(TLObject, TLRequest):
    """
    [Read `account.initPasskeyRegistration` docs](https://core.telegram.org/method/account.initPasskeyRegistration).

    Generated from the following TL definition:
    ```tl
    account.initPasskeyRegistration#429547e8 = account.PasskeyRegistrationOptions
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class InitTakeoutSession(TLObject, TLRequest):
    """
    [Read `account.initTakeoutSession` docs](https://core.telegram.org/method/account.initTakeoutSession).

    Generated from the following TL definition:
    ```tl
    account.initTakeoutSession#8ef3eab0 flags:# contacts:flags.0?true message_users:flags.1?true message_chats:flags.2?true message_megagroups:flags.3?true message_channels:flags.4?true files:flags.5?true file_max_size:flags.5?long = account.Takeout
    ```
    """
    def __new__(
        cls,
        contacts: bool,
        message_users: bool,
        message_chats: bool,
        message_megagroups: bool,
        message_channels: bool,
        files: bool,
        file_max_size: Optional[int],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class RegisterPasskey(TLObject, TLRequest):
    """
    [Read `account.registerPasskey` docs](https://core.telegram.org/method/account.registerPasskey).

    Generated from the following TL definition:
    ```tl
    account.registerPasskey#55b41fd6 credential:InputPasskeyCredential = Passkey
    ```
    """
    def __new__(
        cls,
        credential: types.InputPasskeyCredentialPublicKey
        | types.InputPasskeyCredentialFirebasePnv,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ResetPassword(TLObject, TLRequest):
    """
    [Read `account.resetPassword` docs](https://core.telegram.org/method/account.resetPassword).

    Generated from the following TL definition:
    ```tl
    account.resetPassword#9308ce1b = account.ResetPasswordResult
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ResolveBusinessChatLink(TLObject, TLRequest):
    """
    [Read `account.resolveBusinessChatLink` docs](https://core.telegram.org/method/account.resolveBusinessChatLink).

    Generated from the following TL definition:
    ```tl
    account.resolveBusinessChatLink#5492e5ee slug:string = account.ResolvedBusinessChatLinks
    ```
    """
    def __new__(
        cls,
        slug: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SaveRingtone(TLObject, TLRequest):
    """
    [Read `account.saveRingtone` docs](https://core.telegram.org/method/account.saveRingtone).

    Generated from the following TL definition:
    ```tl
    account.saveRingtone#3dea5b03 id:InputDocument unsave:Bool = account.SavedRingtone
    ```
    """
    def __new__(
        cls,
        id: types.InputDocumentEmpty | types.InputDocument,
        unsave: bool,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SaveSecureValue(TLObject, TLRequest):
    """
    [Read `account.saveSecureValue` docs](https://core.telegram.org/method/account.saveSecureValue).

    Generated from the following TL definition:
    ```tl
    account.saveSecureValue#899fe31d value:InputSecureValue secure_secret_id:long = SecureValue
    ```
    """
    def __new__(
        cls,
        value: types.InputSecureValue,
        secure_secret_id: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SendChangePhoneCode(TLObject, TLRequest):
    """
    [Read `account.sendChangePhoneCode` docs](https://core.telegram.org/method/account.sendChangePhoneCode).

    Generated from the following TL definition:
    ```tl
    account.sendChangePhoneCode#82574ae5 phone_number:string settings:CodeSettings = auth.SentCode
    ```
    """
    def __new__(
        cls,
        phone_number: str,
        settings: types.CodeSettings,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SendConfirmPhoneCode(TLObject, TLRequest):
    """
    [Read `account.sendConfirmPhoneCode` docs](https://core.telegram.org/method/account.sendConfirmPhoneCode).

    Generated from the following TL definition:
    ```tl
    account.sendConfirmPhoneCode#1b3faa88 hash:string settings:CodeSettings = auth.SentCode
    ```
    """
    def __new__(
        cls,
        hash: str,
        settings: types.CodeSettings,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SendVerifyEmailCode(TLObject, TLRequest):
    """
    [Read `account.sendVerifyEmailCode` docs](https://core.telegram.org/method/account.sendVerifyEmailCode).

    Generated from the following TL definition:
    ```tl
    account.sendVerifyEmailCode#98e037bb purpose:EmailVerifyPurpose email:string = account.SentEmailCode
    ```
    """
    def __new__(
        cls,
        purpose: types.EmailVerifyPurposeLoginSetup
        | types.EmailVerifyPurposeLoginChange
        | types.EmailVerifyPurposePassport,
        email: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SendVerifyPhoneCode(TLObject, TLRequest):
    """
    [Read `account.sendVerifyPhoneCode` docs](https://core.telegram.org/method/account.sendVerifyPhoneCode).

    Generated from the following TL definition:
    ```tl
    account.sendVerifyPhoneCode#a5a356f9 phone_number:string settings:CodeSettings = auth.SentCode
    ```
    """
    def __new__(
        cls,
        phone_number: str,
        settings: types.CodeSettings,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SetGlobalPrivacySettings(TLObject, TLRequest):
    """
    [Read `account.setGlobalPrivacySettings` docs](https://core.telegram.org/method/account.setGlobalPrivacySettings).

    Generated from the following TL definition:
    ```tl
    account.setGlobalPrivacySettings#1edaaac2 settings:GlobalPrivacySettings = GlobalPrivacySettings
    ```
    """
    def __new__(
        cls,
        settings: types.GlobalPrivacySettings,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SetPrivacy(TLObject, TLRequest):
    """
    [Read `account.setPrivacy` docs](https://core.telegram.org/method/account.setPrivacy).

    Generated from the following TL definition:
    ```tl
    account.setPrivacy#c9f81ce8 key:InputPrivacyKey rules:Vector<InputPrivacyRule> = account.PrivacyRules
    ```
    """
    def __new__(
        cls,
        key: types.InputPrivacyKeyStatusTimestamp
        | types.InputPrivacyKeyChatInvite
        | types.InputPrivacyKeyPhoneCall
        | types.InputPrivacyKeyPhoneP2P
        | types.InputPrivacyKeyForwards
        | types.InputPrivacyKeyProfilePhoto
        | types.InputPrivacyKeyPhoneNumber
        | types.InputPrivacyKeyAddedByPhone
        | types.InputPrivacyKeyVoiceMessages
        | types.InputPrivacyKeyAbout
        | types.InputPrivacyKeyBirthday
        | types.InputPrivacyKeyStarGiftsAutoSave
        | types.InputPrivacyKeyNoPaidMessages
        | types.InputPrivacyKeySavedMusic,
        rules: Sequence[
            types.InputPrivacyValueAllowContacts
            | types.InputPrivacyValueAllowAll
            | types.InputPrivacyValueAllowUsers
            | types.InputPrivacyValueDisallowContacts
            | types.InputPrivacyValueDisallowAll
            | types.InputPrivacyValueDisallowUsers
            | types.InputPrivacyValueAllowChatParticipants
            | types.InputPrivacyValueDisallowChatParticipants
            | types.InputPrivacyValueAllowCloseFriends
            | types.InputPrivacyValueAllowPremium
            | types.InputPrivacyValueAllowBots
            | types.InputPrivacyValueDisallowBots
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SetReactionsNotifySettings(TLObject, TLRequest):
    """
    [Read `account.setReactionsNotifySettings` docs](https://core.telegram.org/method/account.setReactionsNotifySettings).

    Generated from the following TL definition:
    ```tl
    account.setReactionsNotifySettings#316ce548 settings:ReactionsNotifySettings = ReactionsNotifySettings
    ```
    """
    def __new__(
        cls,
        settings: types.ReactionsNotifySettings,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UpdateConnectedBot(TLObject, TLRequest):
    """
    [Read `account.updateConnectedBot` docs](https://core.telegram.org/method/account.updateConnectedBot).

    Generated from the following TL definition:
    ```tl
    account.updateConnectedBot#66a08c7e flags:# deleted:flags.1?true rights:flags.0?BusinessBotRights bot:InputUser recipients:InputBusinessBotRecipients = Updates
    ```
    """
    def __new__(
        cls,
        deleted: bool,
        rights: Optional[types.BusinessBotRights],
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        recipients: types.InputBusinessBotRecipients,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UpdateProfile(TLObject, TLRequest):
    """
    [Read `account.updateProfile` docs](https://core.telegram.org/method/account.updateProfile).

    Generated from the following TL definition:
    ```tl
    account.updateProfile#78515775 flags:# first_name:flags.0?string last_name:flags.1?string about:flags.2?string = User
    ```
    """
    def __new__(
        cls,
        first_name: Optional[str],
        last_name: Optional[str],
        about: Optional[str],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UpdateTheme(TLObject, TLRequest):
    """
    [Read `account.updateTheme` docs](https://core.telegram.org/method/account.updateTheme).

    Generated from the following TL definition:
    ```tl
    account.updateTheme#2bf40ccc flags:# format:string theme:InputTheme slug:flags.0?string title:flags.1?string document:flags.2?InputDocument settings:flags.3?Vector<InputThemeSettings> = Theme
    ```
    """
    def __new__(
        cls,
        format: str,
        theme: types.InputTheme | types.InputThemeSlug,
        slug: Optional[str],
        title: Optional[str],
        document: Optional[types.InputDocumentEmpty | types.InputDocument],
        settings: Optional[Sequence[types.InputThemeSettings]],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UpdateUsername(TLObject, TLRequest):
    """
    [Read `account.updateUsername` docs](https://core.telegram.org/method/account.updateUsername).

    Generated from the following TL definition:
    ```tl
    account.updateUsername#3e0bdd7c username:string = User
    ```
    """
    def __new__(
        cls,
        username: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UploadRingtone(TLObject, TLRequest):
    """
    [Read `account.uploadRingtone` docs](https://core.telegram.org/method/account.uploadRingtone).

    Generated from the following TL definition:
    ```tl
    account.uploadRingtone#831a83a2 file:InputFile file_name:string mime_type:string = Document
    ```
    """
    def __new__(
        cls,
        file: types.InputFile | types.InputFileBig | types.InputFileStoryDocument,
        file_name: str,
        mime_type: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UploadTheme(TLObject, TLRequest):
    """
    [Read `account.uploadTheme` docs](https://core.telegram.org/method/account.uploadTheme).

    Generated from the following TL definition:
    ```tl
    account.uploadTheme#1c3db333 flags:# file:InputFile thumb:flags.0?InputFile file_name:string mime_type:string = Document
    ```
    """
    def __new__(
        cls,
        file: types.InputFile | types.InputFileBig | types.InputFileStoryDocument,
        thumb: Optional[
            types.InputFile | types.InputFileBig | types.InputFileStoryDocument
        ],
        file_name: str,
        mime_type: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UploadWallPaper(TLObject, TLRequest):
    """
    [Read `account.uploadWallPaper` docs](https://core.telegram.org/method/account.uploadWallPaper).

    Generated from the following TL definition:
    ```tl
    account.uploadWallPaper#e39a8f03 flags:# for_chat:flags.0?true file:InputFile mime_type:string settings:WallPaperSettings = WallPaper
    ```
    """
    def __new__(
        cls,
        for_chat: bool,
        file: types.InputFile | types.InputFileBig | types.InputFileStoryDocument,
        mime_type: str,
        settings: types.WallPaperSettings,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class VerifyEmail(TLObject, TLRequest):
    """
    [Read `account.verifyEmail` docs](https://core.telegram.org/method/account.verifyEmail).

    Generated from the following TL definition:
    ```tl
    account.verifyEmail#32da4cf purpose:EmailVerifyPurpose verification:EmailVerification = account.EmailVerified
    ```
    """
    def __new__(
        cls,
        purpose: types.EmailVerifyPurposeLoginSetup
        | types.EmailVerifyPurposeLoginChange
        | types.EmailVerifyPurposePassport,
        verification: types.EmailVerificationCode
        | types.EmailVerificationGoogle
        | types.EmailVerificationApple,
    ) -> Self: ...
    def to_dict(self) -> dict: ...
