"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLRequest, types

@final
class CreateTone(TLRequest):
    """
    [Read `aicompose.createTone` docs](https://core.telegram.org/method/aicompose.createTone).

    Generated from the following TL definition:
    ```tl
    aicompose.createTone#4aa83913 flags:# display_author:flags.0?true emoji_id:long title:string prompt:string = AiComposeTone
    ```
    """
    def __new__(
        cls,
        display_author: bool,
        emoji_id: int,
        title: str,
        prompt: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UpdateTone(TLRequest):
    """
    [Read `aicompose.updateTone` docs](https://core.telegram.org/method/aicompose.updateTone).

    Generated from the following TL definition:
    ```tl
    aicompose.updateTone#903bcf59 flags:# tone:InputAiComposeTone display_author:flags.0?Bool emoji_id:flags.1?long title:flags.2?string prompt:flags.3?string = AiComposeTone
    ```
    """
    def __new__(
        cls,
        tone: types.InputAiComposeToneDefault
        | types.InputAiComposeToneId
        | types.InputAiComposeToneSlug,
        display_author: Optional[bool],
        emoji_id: Optional[int],
        title: Optional[str],
        prompt: Optional[str],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SaveTone(TLRequest):
    """
    [Read `aicompose.saveTone` docs](https://core.telegram.org/method/aicompose.saveTone).

    Generated from the following TL definition:
    ```tl
    aicompose.saveTone#1782cbb1 tone:InputAiComposeTone unsave:Bool = Bool
    ```
    """
    def __new__(
        cls,
        tone: types.InputAiComposeToneDefault
        | types.InputAiComposeToneId
        | types.InputAiComposeToneSlug,
        unsave: bool,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class DeleteTone(TLRequest):
    """
    [Read `aicompose.deleteTone` docs](https://core.telegram.org/method/aicompose.deleteTone).

    Generated from the following TL definition:
    ```tl
    aicompose.deleteTone#dd39316a tone:InputAiComposeTone = Bool
    ```
    """
    def __new__(
        cls,
        tone: types.InputAiComposeToneDefault
        | types.InputAiComposeToneId
        | types.InputAiComposeToneSlug,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetTone(TLRequest):
    """
    [Read `aicompose.getTone` docs](https://core.telegram.org/method/aicompose.getTone).

    Generated from the following TL definition:
    ```tl
    aicompose.getTone#b2e8ba03 tone:InputAiComposeTone = aicompose.Tones
    ```
    """
    def __new__(
        cls,
        tone: types.InputAiComposeToneDefault
        | types.InputAiComposeToneId
        | types.InputAiComposeToneSlug,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetTones(TLRequest):
    """
    [Read `aicompose.getTones` docs](https://core.telegram.org/method/aicompose.getTones).

    Generated from the following TL definition:
    ```tl
    aicompose.getTones#abd59201 hash:long = aicompose.Tones
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetToneExample(TLRequest):
    """
    [Read `aicompose.getToneExample` docs](https://core.telegram.org/method/aicompose.getToneExample).

    Generated from the following TL definition:
    ```tl
    aicompose.getToneExample#d1b4ab14 tone:InputAiComposeTone num:int = AiComposeToneExample
    ```
    """
    def __new__(
        cls,
        tone: types.InputAiComposeToneDefault
        | types.InputAiComposeToneId
        | types.InputAiComposeToneSlug,
        num: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...
