"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class AddPreviewMedia(TLObject, TLRequest):
    """
    [Read `bots.addPreviewMedia` docs](https://core.telegram.org/method/bots.addPreviewMedia).

    Generated from the following TL definition:
    ```tl
    bots.addPreviewMedia#17aeb75a bot:InputUser lang_code:string media:InputMedia = BotPreviewMedia
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        lang_code: str,
        media: types.InputMediaEmpty
        | types.InputMediaUploadedPhoto
        | types.InputMediaPhoto
        | types.InputMediaGeoPoint
        | types.InputMediaContact
        | types.InputMediaUploadedDocument
        | types.InputMediaDocument
        | types.InputMediaVenue
        | types.InputMediaPhotoExternal
        | types.InputMediaDocumentExternal
        | types.InputMediaGame
        | types.InputMediaInvoice
        | types.InputMediaGeoLive
        | types.InputMediaPoll
        | types.InputMediaDice
        | types.InputMediaStory
        | types.InputMediaWebPage
        | types.InputMediaPaidMedia
        | types.InputMediaTodo
        | types.InputMediaStakeDice,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class AllowSendMessage(TLObject, TLRequest):
    """
    [Read `bots.allowSendMessage` docs](https://core.telegram.org/method/bots.allowSendMessage).

    Generated from the following TL definition:
    ```tl
    bots.allowSendMessage#f132e3ef bot:InputUser = Updates
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class CreateBot(TLObject, TLRequest):
    """
    [Read `bots.createBot` docs](https://core.telegram.org/method/bots.createBot).

    Generated from the following TL definition:
    ```tl
    bots.createBot#e5b17f2b flags:# via_deeplink:flags.0?true name:string username:string manager_id:InputUser = User
    ```
    """
    def __new__(
        cls,
        via_deeplink: bool,
        name: str,
        username: str,
        manager_id: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class EditPreviewMedia(TLObject, TLRequest):
    """
    [Read `bots.editPreviewMedia` docs](https://core.telegram.org/method/bots.editPreviewMedia).

    Generated from the following TL definition:
    ```tl
    bots.editPreviewMedia#8525606f bot:InputUser lang_code:string media:InputMedia new_media:InputMedia = BotPreviewMedia
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        lang_code: str,
        media: types.InputMediaEmpty
        | types.InputMediaUploadedPhoto
        | types.InputMediaPhoto
        | types.InputMediaGeoPoint
        | types.InputMediaContact
        | types.InputMediaUploadedDocument
        | types.InputMediaDocument
        | types.InputMediaVenue
        | types.InputMediaPhotoExternal
        | types.InputMediaDocumentExternal
        | types.InputMediaGame
        | types.InputMediaInvoice
        | types.InputMediaGeoLive
        | types.InputMediaPoll
        | types.InputMediaDice
        | types.InputMediaStory
        | types.InputMediaWebPage
        | types.InputMediaPaidMedia
        | types.InputMediaTodo
        | types.InputMediaStakeDice,
        new_media: types.InputMediaEmpty
        | types.InputMediaUploadedPhoto
        | types.InputMediaPhoto
        | types.InputMediaGeoPoint
        | types.InputMediaContact
        | types.InputMediaUploadedDocument
        | types.InputMediaDocument
        | types.InputMediaVenue
        | types.InputMediaPhotoExternal
        | types.InputMediaDocumentExternal
        | types.InputMediaGame
        | types.InputMediaInvoice
        | types.InputMediaGeoLive
        | types.InputMediaPoll
        | types.InputMediaDice
        | types.InputMediaStory
        | types.InputMediaWebPage
        | types.InputMediaPaidMedia
        | types.InputMediaTodo
        | types.InputMediaStakeDice,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ExportBotToken(TLObject, TLRequest):
    """
    [Read `bots.exportBotToken` docs](https://core.telegram.org/method/bots.exportBotToken).

    Generated from the following TL definition:
    ```tl
    bots.exportBotToken#bd0d99eb bot:InputUser revoke:Bool = bots.ExportedBotToken
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        revoke: bool,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAccessSettings(TLObject, TLRequest):
    """
    [Read `bots.getAccessSettings` docs](https://core.telegram.org/method/bots.getAccessSettings).

    Generated from the following TL definition:
    ```tl
    bots.getAccessSettings#213853a3 bot:InputUser = bots.AccessSettings
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAdminedBots(TLObject, TLRequest):
    """
    [Read `bots.getAdminedBots` docs](https://core.telegram.org/method/bots.getAdminedBots).

    Generated from the following TL definition:
    ```tl
    bots.getAdminedBots#b0711d83 = Vector<User>
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetBotCommands(TLObject, TLRequest):
    """
    [Read `bots.getBotCommands` docs](https://core.telegram.org/method/bots.getBotCommands).

    Generated from the following TL definition:
    ```tl
    bots.getBotCommands#e34c0dd6 scope:BotCommandScope lang_code:string = Vector<BotCommand>
    ```
    """
    def __new__(
        cls,
        scope: types.BotCommandScopeDefault
        | types.BotCommandScopeUsers
        | types.BotCommandScopeChats
        | types.BotCommandScopeChatAdmins
        | types.BotCommandScopePeer
        | types.BotCommandScopePeerAdmins
        | types.BotCommandScopePeerUser,
        lang_code: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetBotInfo(TLObject, TLRequest):
    """
    [Read `bots.getBotInfo` docs](https://core.telegram.org/method/bots.getBotInfo).

    Generated from the following TL definition:
    ```tl
    bots.getBotInfo#dcd914fd flags:# bot:flags.0?InputUser lang_code:string = bots.BotInfo
    ```
    """
    def __new__(
        cls,
        bot: Optional[
            types.InputUserEmpty
            | types.InputUserSelf
            | types.InputUser
            | types.InputUserFromMessage
        ],
        lang_code: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetBotMenuButton(TLObject, TLRequest):
    """
    [Read `bots.getBotMenuButton` docs](https://core.telegram.org/method/bots.getBotMenuButton).

    Generated from the following TL definition:
    ```tl
    bots.getBotMenuButton#9c60eb28 user_id:InputUser = BotMenuButton
    ```
    """
    def __new__(
        cls,
        user_id: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetBotRecommendations(TLObject, TLRequest):
    """
    [Read `bots.getBotRecommendations` docs](https://core.telegram.org/method/bots.getBotRecommendations).

    Generated from the following TL definition:
    ```tl
    bots.getBotRecommendations#a1b70815 bot:InputUser = users.Users
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPopularAppBots(TLObject, TLRequest):
    """
    [Read `bots.getPopularAppBots` docs](https://core.telegram.org/method/bots.getPopularAppBots).

    Generated from the following TL definition:
    ```tl
    bots.getPopularAppBots#c2510192 offset:string limit:int = bots.PopularAppBots
    ```
    """
    def __new__(
        cls,
        offset: str,
        limit: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPreviewInfo(TLObject, TLRequest):
    """
    [Read `bots.getPreviewInfo` docs](https://core.telegram.org/method/bots.getPreviewInfo).

    Generated from the following TL definition:
    ```tl
    bots.getPreviewInfo#423ab3ad bot:InputUser lang_code:string = bots.PreviewInfo
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        lang_code: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPreviewMedias(TLObject, TLRequest):
    """
    [Read `bots.getPreviewMedias` docs](https://core.telegram.org/method/bots.getPreviewMedias).

    Generated from the following TL definition:
    ```tl
    bots.getPreviewMedias#a2a5594d bot:InputUser = Vector<BotPreviewMedia>
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetRequestedWebViewButton(TLObject, TLRequest):
    """
    [Read `bots.getRequestedWebViewButton` docs](https://core.telegram.org/method/bots.getRequestedWebViewButton).

    Generated from the following TL definition:
    ```tl
    bots.getRequestedWebViewButton#bf25b7f3 bot:InputUser webapp_req_id:string = KeyboardButton
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        webapp_req_id: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class InvokeWebViewCustomMethod(TLObject, TLRequest):
    """
    [Read `bots.invokeWebViewCustomMethod` docs](https://core.telegram.org/method/bots.invokeWebViewCustomMethod).

    Generated from the following TL definition:
    ```tl
    bots.invokeWebViewCustomMethod#87fc5e7 bot:InputUser custom_method:string params:DataJSON = DataJSON
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        custom_method: str,
        params: types.DataJson,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class RequestWebViewButton(TLObject, TLRequest):
    """
    [Read `bots.requestWebViewButton` docs](https://core.telegram.org/method/bots.requestWebViewButton).

    Generated from the following TL definition:
    ```tl
    bots.requestWebViewButton#31a2a35e user_id:InputUser button:KeyboardButton = bots.RequestedButton
    ```
    """
    def __new__(
        cls,
        user_id: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        button: types.KeyboardButton
        | types.KeyboardButtonUrl
        | types.KeyboardButtonCallback
        | types.KeyboardButtonRequestPhone
        | types.KeyboardButtonRequestGeoLocation
        | types.KeyboardButtonSwitchInline
        | types.KeyboardButtonGame
        | types.KeyboardButtonBuy
        | types.KeyboardButtonUrlAuth
        | types.InputKeyboardButtonUrlAuth
        | types.KeyboardButtonRequestPoll
        | types.InputKeyboardButtonUserProfile
        | types.KeyboardButtonUserProfile
        | types.KeyboardButtonWebView
        | types.KeyboardButtonSimpleWebView
        | types.KeyboardButtonRequestPeer
        | types.InputKeyboardButtonRequestPeer
        | types.KeyboardButtonCopy,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class SendCustomRequest(TLObject, TLRequest):
    """
    [Read `bots.sendCustomRequest` docs](https://core.telegram.org/method/bots.sendCustomRequest).

    Generated from the following TL definition:
    ```tl
    bots.sendCustomRequest#aa2769ed custom_method:string params:DataJSON = DataJSON
    ```
    """
    def __new__(
        cls,
        custom_method: str,
        params: types.DataJson,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class UpdateStarRefProgram(TLObject, TLRequest):
    """
    [Read `bots.updateStarRefProgram` docs](https://core.telegram.org/method/bots.updateStarRefProgram).

    Generated from the following TL definition:
    ```tl
    bots.updateStarRefProgram#778b5ab3 flags:# bot:InputUser commission_permille:int duration_months:flags.0?int = StarRefProgram
    ```
    """
    def __new__(
        cls,
        bot: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        commission_permille: int,
        duration_months: Optional[int],
    ) -> Self: ...
    def to_dict(self) -> dict: ...
