"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class CheckChatlistInvite(TLObject, TLRequest):
    """
    [Read `chatlists.checkChatlistInvite` docs](https://core.telegram.org/method/chatlists.checkChatlistInvite).

    Generated from the following TL definition:
    ```tl
    chatlists.checkChatlistInvite#41c10fff slug:string = chatlists.ChatlistInvite
    ```
    """
    def __new__(
        cls,
        slug: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class EditExportedInvite(TLObject, TLRequest):
    """
    [Read `chatlists.editExportedInvite` docs](https://core.telegram.org/method/chatlists.editExportedInvite).

    Generated from the following TL definition:
    ```tl
    chatlists.editExportedInvite#653db63d flags:# chatlist:InputChatlist slug:string title:flags.1?string peers:flags.2?Vector<InputPeer> = ExportedChatlistInvite
    ```
    """
    def __new__(
        cls,
        chatlist: types.InputChatlistDialogFilter,
        slug: str,
        title: Optional[str],
        peers: Optional[
            Sequence[
                types.InputPeerEmpty
                | types.InputPeerSelf
                | types.InputPeerChat
                | types.InputPeerUser
                | types.InputPeerChannel
                | types.InputPeerUserFromMessage
                | types.InputPeerChannelFromMessage
            ]
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ExportChatlistInvite(TLObject, TLRequest):
    """
    [Read `chatlists.exportChatlistInvite` docs](https://core.telegram.org/method/chatlists.exportChatlistInvite).

    Generated from the following TL definition:
    ```tl
    chatlists.exportChatlistInvite#8472478e chatlist:InputChatlist title:string peers:Vector<InputPeer> = chatlists.ExportedChatlistInvite
    ```
    """
    def __new__(
        cls,
        chatlist: types.InputChatlistDialogFilter,
        title: str,
        peers: Sequence[
            types.InputPeerEmpty
            | types.InputPeerSelf
            | types.InputPeerChat
            | types.InputPeerUser
            | types.InputPeerChannel
            | types.InputPeerUserFromMessage
            | types.InputPeerChannelFromMessage
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetChatlistUpdates(TLObject, TLRequest):
    """
    [Read `chatlists.getChatlistUpdates` docs](https://core.telegram.org/method/chatlists.getChatlistUpdates).

    Generated from the following TL definition:
    ```tl
    chatlists.getChatlistUpdates#89419521 chatlist:InputChatlist = chatlists.ChatlistUpdates
    ```
    """
    def __new__(
        cls,
        chatlist: types.InputChatlistDialogFilter,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetExportedInvites(TLObject, TLRequest):
    """
    [Read `chatlists.getExportedInvites` docs](https://core.telegram.org/method/chatlists.getExportedInvites).

    Generated from the following TL definition:
    ```tl
    chatlists.getExportedInvites#ce03da83 chatlist:InputChatlist = chatlists.ExportedInvites
    ```
    """
    def __new__(
        cls,
        chatlist: types.InputChatlistDialogFilter,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetLeaveChatlistSuggestions(TLObject, TLRequest):
    """
    [Read `chatlists.getLeaveChatlistSuggestions` docs](https://core.telegram.org/method/chatlists.getLeaveChatlistSuggestions).

    Generated from the following TL definition:
    ```tl
    chatlists.getLeaveChatlistSuggestions#fdbcd714 chatlist:InputChatlist = Vector<Peer>
    ```
    """
    def __new__(
        cls,
        chatlist: types.InputChatlistDialogFilter,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class JoinChatlistInvite(TLObject, TLRequest):
    """
    [Read `chatlists.joinChatlistInvite` docs](https://core.telegram.org/method/chatlists.joinChatlistInvite).

    Generated from the following TL definition:
    ```tl
    chatlists.joinChatlistInvite#a6b1e39a slug:string peers:Vector<InputPeer> = Updates
    ```
    """
    def __new__(
        cls,
        slug: str,
        peers: Sequence[
            types.InputPeerEmpty
            | types.InputPeerSelf
            | types.InputPeerChat
            | types.InputPeerUser
            | types.InputPeerChannel
            | types.InputPeerUserFromMessage
            | types.InputPeerChannelFromMessage
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class JoinChatlistUpdates(TLObject, TLRequest):
    """
    [Read `chatlists.joinChatlistUpdates` docs](https://core.telegram.org/method/chatlists.joinChatlistUpdates).

    Generated from the following TL definition:
    ```tl
    chatlists.joinChatlistUpdates#e089f8f5 chatlist:InputChatlist peers:Vector<InputPeer> = Updates
    ```
    """
    def __new__(
        cls,
        chatlist: types.InputChatlistDialogFilter,
        peers: Sequence[
            types.InputPeerEmpty
            | types.InputPeerSelf
            | types.InputPeerChat
            | types.InputPeerUser
            | types.InputPeerChannel
            | types.InputPeerUserFromMessage
            | types.InputPeerChannelFromMessage
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class LeaveChatlist(TLObject, TLRequest):
    """
    [Read `chatlists.leaveChatlist` docs](https://core.telegram.org/method/chatlists.leaveChatlist).

    Generated from the following TL definition:
    ```tl
    chatlists.leaveChatlist#74fae13a chatlist:InputChatlist peers:Vector<InputPeer> = Updates
    ```
    """
    def __new__(
        cls,
        chatlist: types.InputChatlistDialogFilter,
        peers: Sequence[
            types.InputPeerEmpty
            | types.InputPeerSelf
            | types.InputPeerChat
            | types.InputPeerUser
            | types.InputPeerChannel
            | types.InputPeerUserFromMessage
            | types.InputPeerChannelFromMessage
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...
