"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class AcceptContact(TLObject, TLRequest):
    """
    [Read `contacts.acceptContact` docs](https://core.telegram.org/method/contacts.acceptContact).

    Generated from the following TL definition:
    ```tl
    contacts.acceptContact#f831a20f id:InputUser = Updates
    ```
    """
    def __new__(
        cls,
        id: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class AddContact(TLObject, TLRequest):
    """
    [Read `contacts.addContact` docs](https://core.telegram.org/method/contacts.addContact).

    Generated from the following TL definition:
    ```tl
    contacts.addContact#d9ba2e54 flags:# add_phone_privacy_exception:flags.0?true id:InputUser first_name:string last_name:string phone:string note:flags.1?TextWithEntities = Updates
    ```
    """
    def __new__(
        cls,
        add_phone_privacy_exception: bool,
        id: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        first_name: str,
        last_name: str,
        phone: str,
        note: Optional[types.TextWithEntities],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class BlockFromReplies(TLObject, TLRequest):
    """
    [Read `contacts.blockFromReplies` docs](https://core.telegram.org/method/contacts.blockFromReplies).

    Generated from the following TL definition:
    ```tl
    contacts.blockFromReplies#29a8962c flags:# delete_message:flags.0?true delete_history:flags.1?true report_spam:flags.2?true msg_id:int = Updates
    ```
    """
    def __new__(
        cls,
        delete_message: bool,
        delete_history: bool,
        report_spam: bool,
        msg_id: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class DeleteContacts(TLObject, TLRequest):
    """
    [Read `contacts.deleteContacts` docs](https://core.telegram.org/method/contacts.deleteContacts).

    Generated from the following TL definition:
    ```tl
    contacts.deleteContacts#96a0e00 id:Vector<InputUser> = Updates
    ```
    """
    def __new__(
        cls,
        id: Sequence[
            types.InputUserEmpty
            | types.InputUserSelf
            | types.InputUser
            | types.InputUserFromMessage
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ExportContactToken(TLObject, TLRequest):
    """
    [Read `contacts.exportContactToken` docs](https://core.telegram.org/method/contacts.exportContactToken).

    Generated from the following TL definition:
    ```tl
    contacts.exportContactToken#f8654027 = ExportedContactToken
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetBirthdays(TLObject, TLRequest):
    """
    [Read `contacts.getBirthdays` docs](https://core.telegram.org/method/contacts.getBirthdays).

    Generated from the following TL definition:
    ```tl
    contacts.getBirthdays#daeda864 = contacts.ContactBirthdays
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetBlocked(TLObject, TLRequest):
    """
    [Read `contacts.getBlocked` docs](https://core.telegram.org/method/contacts.getBlocked).

    Generated from the following TL definition:
    ```tl
    contacts.getBlocked#9a868f80 flags:# my_stories_from:flags.0?true offset:int limit:int = contacts.Blocked
    ```
    """
    def __new__(
        cls,
        my_stories_from: bool,
        offset: int,
        limit: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetContactIds(TLObject, TLRequest):
    """
    [Read `contacts.getContactIDs` docs](https://core.telegram.org/method/contacts.getContactIDs).

    Generated from the following TL definition:
    ```tl
    contacts.getContactIDs#7adc669d hash:long = Vector<int>
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetContacts(TLObject, TLRequest):
    """
    [Read `contacts.getContacts` docs](https://core.telegram.org/method/contacts.getContacts).

    Generated from the following TL definition:
    ```tl
    contacts.getContacts#5dd69e12 hash:long = contacts.Contacts
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetLocated(TLObject, TLRequest):
    """
    [Read `contacts.getLocated` docs](https://core.telegram.org/method/contacts.getLocated).

    Generated from the following TL definition:
    ```tl
    contacts.getLocated#d348bc44 flags:# background:flags.1?true geo_point:InputGeoPoint self_expires:flags.0?int = Updates
    ```
    """
    def __new__(
        cls,
        background: bool,
        geo_point: types.InputGeoPointEmpty | types.InputGeoPoint,
        self_expires: Optional[int],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetSaved(TLObject, TLRequest):
    """
    [Read `contacts.getSaved` docs](https://core.telegram.org/method/contacts.getSaved).

    Generated from the following TL definition:
    ```tl
    contacts.getSaved#82f1e39f = Vector<SavedContact>
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetSponsoredPeers(TLObject, TLRequest):
    """
    [Read `contacts.getSponsoredPeers` docs](https://core.telegram.org/method/contacts.getSponsoredPeers).

    Generated from the following TL definition:
    ```tl
    contacts.getSponsoredPeers#b6c8c393 q:string = contacts.SponsoredPeers
    ```
    """
    def __new__(
        cls,
        q: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetStatuses(TLObject, TLRequest):
    """
    [Read `contacts.getStatuses` docs](https://core.telegram.org/method/contacts.getStatuses).

    Generated from the following TL definition:
    ```tl
    contacts.getStatuses#c4a353ee = Vector<ContactStatus>
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetTopPeers(TLObject, TLRequest):
    """
    [Read `contacts.getTopPeers` docs](https://core.telegram.org/method/contacts.getTopPeers).

    Generated from the following TL definition:
    ```tl
    contacts.getTopPeers#973478b6 flags:# correspondents:flags.0?true bots_pm:flags.1?true bots_inline:flags.2?true phone_calls:flags.3?true forward_users:flags.4?true forward_chats:flags.5?true groups:flags.10?true channels:flags.15?true bots_app:flags.16?true bots_guestchat:flags.17?true offset:int limit:int hash:long = contacts.TopPeers
    ```
    """
    def __new__(
        cls,
        correspondents: bool,
        bots_pm: bool,
        bots_inline: bool,
        phone_calls: bool,
        forward_users: bool,
        forward_chats: bool,
        groups: bool,
        channels: bool,
        bots_app: bool,
        bots_guestchat: bool,
        offset: int,
        limit: int,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ImportContactToken(TLObject, TLRequest):
    """
    [Read `contacts.importContactToken` docs](https://core.telegram.org/method/contacts.importContactToken).

    Generated from the following TL definition:
    ```tl
    contacts.importContactToken#13005788 token:string = User
    ```
    """
    def __new__(
        cls,
        token: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ImportContacts(TLObject, TLRequest):
    """
    [Read `contacts.importContacts` docs](https://core.telegram.org/method/contacts.importContacts).

    Generated from the following TL definition:
    ```tl
    contacts.importContacts#2c800be5 contacts:Vector<InputContact> = contacts.ImportedContacts
    ```
    """
    def __new__(
        cls,
        contacts: Sequence[types.InputPhoneContact],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ResolvePhone(TLObject, TLRequest):
    """
    [Read `contacts.resolvePhone` docs](https://core.telegram.org/method/contacts.resolvePhone).

    Generated from the following TL definition:
    ```tl
    contacts.resolvePhone#8af94344 phone:string = contacts.ResolvedPeer
    ```
    """
    def __new__(
        cls,
        phone: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ResolveUsername(TLObject, TLRequest):
    """
    [Read `contacts.resolveUsername` docs](https://core.telegram.org/method/contacts.resolveUsername).

    Generated from the following TL definition:
    ```tl
    contacts.resolveUsername#725afbbc flags:# username:string referer:flags.0?string = contacts.ResolvedPeer
    ```
    """
    def __new__(
        cls,
        username: str,
        referer: Optional[str],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class Search(TLObject, TLRequest):
    """
    [Read `contacts.search` docs](https://core.telegram.org/method/contacts.search).

    Generated from the following TL definition:
    ```tl
    contacts.search#11f812d8 q:string limit:int = contacts.Found
    ```
    """
    def __new__(
        cls,
        q: str,
        limit: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...
