"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class EditUserInfo(TLObject, TLRequest):
    """
    [Read `help.editUserInfo` docs](https://core.telegram.org/method/help.editUserInfo).

    Generated from the following TL definition:
    ```tl
    help.editUserInfo#66b91b70 user_id:InputUser message:string entities:Vector<MessageEntity> = help.UserInfo
    ```
    """
    def __new__(
        cls,
        user_id: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
        message: str,
        entities: Sequence[
            types.MessageEntityUnknown
            | types.MessageEntityMention
            | types.MessageEntityHashtag
            | types.MessageEntityBotCommand
            | types.MessageEntityUrl
            | types.MessageEntityEmail
            | types.MessageEntityBold
            | types.MessageEntityItalic
            | types.MessageEntityCode
            | types.MessageEntityPre
            | types.MessageEntityTextUrl
            | types.MessageEntityMentionName
            | types.InputMessageEntityMentionName
            | types.MessageEntityPhone
            | types.MessageEntityCashtag
            | types.MessageEntityUnderline
            | types.MessageEntityStrike
            | types.MessageEntityBankCard
            | types.MessageEntitySpoiler
            | types.MessageEntityCustomEmoji
            | types.MessageEntityBlockquote
            | types.MessageEntityFormattedDate
            | types.MessageEntityDiffInsert
            | types.MessageEntityDiffReplace
            | types.MessageEntityDiffDelete
        ],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAppConfig(TLObject, TLRequest):
    """
    [Read `help.getAppConfig` docs](https://core.telegram.org/method/help.getAppConfig).

    Generated from the following TL definition:
    ```tl
    help.getAppConfig#61e3f854 hash:int = help.AppConfig
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetAppUpdate(TLObject, TLRequest):
    """
    [Read `help.getAppUpdate` docs](https://core.telegram.org/method/help.getAppUpdate).

    Generated from the following TL definition:
    ```tl
    help.getAppUpdate#522d5a7d source:string = help.AppUpdate
    ```
    """
    def __new__(
        cls,
        source: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetCdnConfig(TLObject, TLRequest):
    """
    [Read `help.getCdnConfig` docs](https://core.telegram.org/method/help.getCdnConfig).

    Generated from the following TL definition:
    ```tl
    help.getCdnConfig#52029342 = CdnConfig
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetConfig(TLObject, TLRequest):
    """
    [Read `help.getConfig` docs](https://core.telegram.org/method/help.getConfig).

    Generated from the following TL definition:
    ```tl
    help.getConfig#c4f9186b = Config
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetCountriesList(TLObject, TLRequest):
    """
    [Read `help.getCountriesList` docs](https://core.telegram.org/method/help.getCountriesList).

    Generated from the following TL definition:
    ```tl
    help.getCountriesList#735787a8 lang_code:string hash:int = help.CountriesList
    ```
    """
    def __new__(
        cls,
        lang_code: str,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetDeepLinkInfo(TLObject, TLRequest):
    """
    [Read `help.getDeepLinkInfo` docs](https://core.telegram.org/method/help.getDeepLinkInfo).

    Generated from the following TL definition:
    ```tl
    help.getDeepLinkInfo#3fedc75f path:string = help.DeepLinkInfo
    ```
    """
    def __new__(
        cls,
        path: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetInviteText(TLObject, TLRequest):
    """
    [Read `help.getInviteText` docs](https://core.telegram.org/method/help.getInviteText).

    Generated from the following TL definition:
    ```tl
    help.getInviteText#4d392343 = help.InviteText
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetNearestDc(TLObject, TLRequest):
    """
    [Read `help.getNearestDc` docs](https://core.telegram.org/method/help.getNearestDc).

    Generated from the following TL definition:
    ```tl
    help.getNearestDc#1fb33026 = NearestDc
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPassportConfig(TLObject, TLRequest):
    """
    [Read `help.getPassportConfig` docs](https://core.telegram.org/method/help.getPassportConfig).

    Generated from the following TL definition:
    ```tl
    help.getPassportConfig#c661ad08 hash:int = help.PassportConfig
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPeerColors(TLObject, TLRequest):
    """
    [Read `help.getPeerColors` docs](https://core.telegram.org/method/help.getPeerColors).

    Generated from the following TL definition:
    ```tl
    help.getPeerColors#da80f42f hash:int = help.PeerColors
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPeerProfileColors(TLObject, TLRequest):
    """
    [Read `help.getPeerProfileColors` docs](https://core.telegram.org/method/help.getPeerProfileColors).

    Generated from the following TL definition:
    ```tl
    help.getPeerProfileColors#abcfa9fd hash:int = help.PeerColors
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPremiumPromo(TLObject, TLRequest):
    """
    [Read `help.getPremiumPromo` docs](https://core.telegram.org/method/help.getPremiumPromo).

    Generated from the following TL definition:
    ```tl
    help.getPremiumPromo#b81b93d4 = help.PremiumPromo
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetPromoData(TLObject, TLRequest):
    """
    [Read `help.getPromoData` docs](https://core.telegram.org/method/help.getPromoData).

    Generated from the following TL definition:
    ```tl
    help.getPromoData#c0977421 = help.PromoData
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetRecentMeUrls(TLObject, TLRequest):
    """
    [Read `help.getRecentMeUrls` docs](https://core.telegram.org/method/help.getRecentMeUrls).

    Generated from the following TL definition:
    ```tl
    help.getRecentMeUrls#3dc0f114 referer:string = help.RecentMeUrls
    ```
    """
    def __new__(
        cls,
        referer: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetSupport(TLObject, TLRequest):
    """
    [Read `help.getSupport` docs](https://core.telegram.org/method/help.getSupport).

    Generated from the following TL definition:
    ```tl
    help.getSupport#9cdf08cd = help.Support
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetSupportName(TLObject, TLRequest):
    """
    [Read `help.getSupportName` docs](https://core.telegram.org/method/help.getSupportName).

    Generated from the following TL definition:
    ```tl
    help.getSupportName#d360e72c = help.SupportName
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetTermsOfServiceUpdate(TLObject, TLRequest):
    """
    [Read `help.getTermsOfServiceUpdate` docs](https://core.telegram.org/method/help.getTermsOfServiceUpdate).

    Generated from the following TL definition:
    ```tl
    help.getTermsOfServiceUpdate#2ca51fd1 = help.TermsOfServiceUpdate
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetTimezonesList(TLObject, TLRequest):
    """
    [Read `help.getTimezonesList` docs](https://core.telegram.org/method/help.getTimezonesList).

    Generated from the following TL definition:
    ```tl
    help.getTimezonesList#49b30240 hash:int = help.TimezonesList
    ```
    """
    def __new__(
        cls,
        hash: int,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetUserInfo(TLObject, TLRequest):
    """
    [Read `help.getUserInfo` docs](https://core.telegram.org/method/help.getUserInfo).

    Generated from the following TL definition:
    ```tl
    help.getUserInfo#38a08d3 user_id:InputUser = help.UserInfo
    ```
    """
    def __new__(
        cls,
        user_id: types.InputUserEmpty
        | types.InputUserSelf
        | types.InputUser
        | types.InputUserFromMessage,
    ) -> Self: ...
    def to_dict(self) -> dict: ...
