"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class GetSmsJob(TLObject, TLRequest):
    """
    [Read `smsjobs.getSmsJob` docs](https://core.telegram.org/method/smsjobs.getSmsJob).

    Generated from the following TL definition:
    ```tl
    smsjobs.getSmsJob#778d902f job_id:string = SmsJob
    ```
    """
    def __new__(
        cls,
        job_id: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class GetStatus(TLObject, TLRequest):
    """
    [Read `smsjobs.getStatus` docs](https://core.telegram.org/method/smsjobs.getStatus).

    Generated from the following TL definition:
    ```tl
    smsjobs.getStatus#10a698e8 = smsjobs.Status
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class IsEligibleToJoin(TLObject, TLRequest):
    """
    [Read `smsjobs.isEligibleToJoin` docs](https://core.telegram.org/method/smsjobs.isEligibleToJoin).

    Generated from the following TL definition:
    ```tl
    smsjobs.isEligibleToJoin#edc39d0 = smsjobs.EligibilityToJoin
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...
