mod metadata;
mod rustifier;

use metadata::Metadata;

use std::collections::HashMap;
use std::env;
use std::fs::{self, File};
use std::io::{self, BufRead, BufReader, BufWriter, Read, Write};
use std::path::PathBuf;

use grammers_tl_parser::parse_tl_file;
use grammers_tl_parser::tl::{Category, Definition, ParameterType, Type};

/// Find the `// LAYER #` comment, and return its value if it's valid.
fn find_layer(file: PathBuf) -> io::Result<Option<i32>> {
    const LAYER_MARK: &str = "LAYER";

    Ok(BufReader::new(File::open(file)?).lines().find_map(|line| {
        let line = line.unwrap();
        if line.trim().starts_with("//") {
            if let Some(pos) = line.find(LAYER_MARK) {
                if let Ok(layer) = line[pos + LAYER_MARK.len()..].trim().parse() {
                    return Some(layer);
                }
            }
        }

        None
    }))
}

fn load_tl(file: PathBuf) -> io::Result<Vec<Definition>> {
    let mut file = File::open(file)?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    Ok(parse_tl_file(&contents)
        .filter_map(|d| match d {
            Ok(d) => Some(d),
            Err(e) => {
                eprintln!("[{}: {}] TL: parse error: {e:?}", file!(), line!());
                None
            }
        })
        .collect())
}

fn find_workspace_root() -> Option<PathBuf> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    let mut current = manifest_dir.as_path();

    loop {
        let cargo_toml = current.join("Cargo.toml");
        if cargo_toml.exists() {
            let content = fs::read_to_string(&cargo_toml).ok()?;
            // 检查是否包含 [workspace] 定义
            if content.contains("[workspace]") {
                return Some(current.to_path_buf());
            }
        }

        // 向上一级目录
        current = current.parent()?;
    }
}

fn main() -> anyhow::Result<()> {
    let root = find_workspace_root().unwrap();
    let tl_dir = root.join("grammers-tl-types-pyo3").join("tl");

    let layer = match find_layer(tl_dir.join("api.tl"))? {
        Some(x) => x,
        None => panic!("no layer information found in api.tl"),
    };

    let definitions = {
        let mut definitions = Vec::new();
        definitions.extend(load_tl(tl_dir.join("api.tl"))?);
        definitions.extend(load_tl(tl_dir.join("mtproto.tl"))?);
        definitions
    };

    let module_dir = root.join("python").join("src").join("grammers");
    generate_python_code(module_dir, &definitions, layer).unwrap();

    Ok(())
}

/// Don't generate types for definitions of this type,
/// since they are "core" types and treated differently.
const SPECIAL_CASED_TYPES: [&str; 2] = ["Bool", "True"];

fn ignore_type(ty: &Type) -> bool {
    SPECIAL_CASED_TYPES.iter().any(|&x| x == ty.name)
}

fn write_pyi(
    tl_dir: PathBuf,
    definitions: Vec<&Definition>,
    metadata: &Metadata,
) -> io::Result<()> {
    fs::create_dir_all(&tl_dir)?;

    let base = match definitions[0].category {
        Category::Types => "TLObject",
        Category::Functions => "TLRequest",
    };
    let mut grouped: HashMap<Option<&str>, Vec<&Definition>> = HashMap::new();

    for def in definitions {
        grouped
            .entry(if def.namespace.is_empty() {
                None
            } else {
                Some(&def.namespace[0])
            })
            .or_default()
            .push(def);
    }
    for (namespace, defs) in grouped {
        let filename = match namespace {
            None => String::from("__init__.pyi"),
            Some(ns) => format!("{}.pyi", ns),
        };
        let file_path = tl_dir.join(&filename);
        let mut file = BufWriter::new(File::create(&file_path)?);
        writeln!(
            file,
            r#""""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import {base}, types
"#
        )?;
        for def in defs {
            let type_name = rustifier::definitions::type_name(def);
            let params = def
                .params
                .iter()
                .filter(|param| match &param.ty {
                    ParameterType::Normal { .. } => true,
                    ParameterType::Flags => false,
                })
                .map(|param| {
                    format!(
                        "\n        {}: {},",
                        rustifier::parameters::py_attr_name(param),
                        rustifier::parameters::py_qual_name(param, metadata),
                    )
                })
                .collect::<Vec<_>>()
                .join("");

            writeln!(
                file,
                r#"@final
class {type_name}({base}):
    """
    [Read `{name}` docs](https://core.telegram.org/{kind}/{name}).

    Generated from the following TL definition:
    ```tl
    {def}
    ```
    """
    def __new__(
        cls,{params}
    ) -> Self: ...
    def to_dict(self) -> dict: ...
"#,
                name = def.full_name(),
                kind = match def.category {
                    Category::Types => "constructor",
                    Category::Functions => "method",
                },
                def = def,
            )?;
        }
    }
    Ok(())
}

pub fn generate_python_code(
    module_dir: PathBuf,
    definitions: &[Definition],
    layer: i32,
) -> io::Result<()> {
    let mut allobjects = BufWriter::new(File::create(module_dir.join("tl").join("allobjects.py"))?);
    writeln!(
        allobjects,
        r#""""File generated by TLObjects' generator. All changes will be ERASED"""

from . import types, functions

LAYER = {layer}

tlobjects = {{"#,
    )?;
    for def in definitions {
        if !ignore_type(&def.ty) {
            writeln!(
                allobjects,
                "    0x{:x}: {}.{}{},",
                def.id,
                match def.category {
                    Category::Types => "types",
                    Category::Functions => "functions",
                },
                if def.namespace.is_empty() {
                    "".to_string()
                } else {
                    def.namespace[0].clone() + "."
                },
                rustifier::definitions::type_name(def),
            )?;
        }
    }
    writeln!(allobjects, "}}")?;
    allobjects.flush()?;

    let metadata = Metadata::new(definitions);

    let tl_dir = module_dir.join("_rs").join("tl");
    write_pyi(
        tl_dir.join("functions"),
        definitions
            .iter()
            .filter(|def| def.category == Category::Functions)
            .collect(),
        &metadata,
    )?;
    write_pyi(
        tl_dir.join("types"),
        definitions
            .iter()
            .filter(|def| def.category == Category::Types && !ignore_type(&def.ty))
            .collect(),
        &metadata,
    )?;
    Ok(())
}
