"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, types

@final
class TonesNotModified(TLObject):
    """
    [Read `aicompose.tonesNotModified` docs](https://core.telegram.org/constructor/aicompose.tonesNotModified).

    Generated from the following TL definition:
    ```tl
    aicompose.tonesNotModified#c1f46103 = aicompose.Tones
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class Tones(TLObject):
    """
    [Read `aicompose.tones` docs](https://core.telegram.org/constructor/aicompose.tones).

    Generated from the following TL definition:
    ```tl
    aicompose.tones#6c9d0efe hash:long tones:Vector<AiComposeTone> users:Vector<User> = aicompose.Tones
    ```
    """
    def __new__(
        cls,
        hash: int,
        tones: Sequence[types.AiComposeTone | types.AiComposeToneDefault],
        users: Sequence[types.UserEmpty | types.User],
    ) -> Self: ...
    def to_dict(self) -> dict: ...
