"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, types

@final
class BotInfo(TLObject):
    """
    [Read `bots.botInfo` docs](https://core.telegram.org/constructor/bots.botInfo).

    Generated from the following TL definition:
    ```tl
    bots.botInfo#e8a775b0 name:string about:string description:string = bots.BotInfo
    ```
    """
    def __new__(
        cls,
        name: str,
        about: str,
        description: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class PopularAppBots(TLObject):
    """
    [Read `bots.popularAppBots` docs](https://core.telegram.org/constructor/bots.popularAppBots).

    Generated from the following TL definition:
    ```tl
    bots.popularAppBots#1991b13b flags:# next_offset:flags.0?string users:Vector<User> = bots.PopularAppBots
    ```
    """
    def __new__(
        cls,
        next_offset: Optional[str],
        users: Sequence[types.UserEmpty | types.User],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class PreviewInfo(TLObject):
    """
    [Read `bots.previewInfo` docs](https://core.telegram.org/constructor/bots.previewInfo).

    Generated from the following TL definition:
    ```tl
    bots.previewInfo#ca71d64 media:Vector<BotPreviewMedia> lang_codes:Vector<string> = bots.PreviewInfo
    ```
    """
    def __new__(
        cls,
        media: Sequence[types.BotPreviewMedia],
        lang_codes: Sequence[str],
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class ExportedBotToken(TLObject):
    """
    [Read `bots.exportedBotToken` docs](https://core.telegram.org/constructor/bots.exportedBotToken).

    Generated from the following TL definition:
    ```tl
    bots.exportedBotToken#3c60b621 token:string = bots.ExportedBotToken
    ```
    """
    def __new__(
        cls,
        token: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class RequestedButton(TLObject):
    """
    [Read `bots.requestedButton` docs](https://core.telegram.org/constructor/bots.requestedButton).

    Generated from the following TL definition:
    ```tl
    bots.requestedButton#f13bbcd7 webapp_req_id:string = bots.RequestedButton
    ```
    """
    def __new__(
        cls,
        webapp_req_id: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class AccessSettings(TLObject):
    """
    [Read `bots.accessSettings` docs](https://core.telegram.org/constructor/bots.accessSettings).

    Generated from the following TL definition:
    ```tl
    bots.accessSettings#dd1fbf93 flags:# restricted:flags.0?true add_users:flags.1?Vector<User> = bots.AccessSettings
    ```
    """
    def __new__(
        cls,
        restricted: bool,
        add_users: Optional[Sequence[types.UserEmpty | types.User]],
    ) -> Self: ...
    def to_dict(self) -> dict: ...
