"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class CollectibleInfo(TLObject, TLRequest):
    """
    [Read `fragment.collectibleInfo` docs](https://core.telegram.org/constructor/fragment.collectibleInfo).

    Generated from the following TL definition:
    ```tl
    fragment.collectibleInfo#6ebdff91 purchase_date:int currency:string amount:long crypto_currency:string crypto_amount:long url:string = fragment.CollectibleInfo
    ```
    """
    def __new__(
        cls,
        purchase_date: int,
        currency: str,
        amount: int,
        crypto_currency: str,
        crypto_amount: int,
        url: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...
