"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class SuggestedShortName(TLObject, TLRequest):
    """
    [Read `stickers.suggestedShortName` docs](https://core.telegram.org/constructor/stickers.suggestedShortName).

    Generated from the following TL definition:
    ```tl
    stickers.suggestedShortName#85fea03f short_name:string = stickers.SuggestedShortName
    ```
    """
    def __new__(
        cls,
        short_name: str,
    ) -> Self: ...
    def to_dict(self) -> dict: ...
