"""File generated by TLObjects' generator. All changes will be ERASED"""
# ruff: noqa: F401

from typing import final, Self, Sequence, Optional
from grammers.tl import TLObject, TLRequest, types

@final
class FileGif(TLObject, TLRequest):
    """
    [Read `storage.fileGif` docs](https://core.telegram.org/constructor/storage.fileGif).

    Generated from the following TL definition:
    ```tl
    storage.fileGif#cae1aadf = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FileJpeg(TLObject, TLRequest):
    """
    [Read `storage.fileJpeg` docs](https://core.telegram.org/constructor/storage.fileJpeg).

    Generated from the following TL definition:
    ```tl
    storage.fileJpeg#7efe0e = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FileMov(TLObject, TLRequest):
    """
    [Read `storage.fileMov` docs](https://core.telegram.org/constructor/storage.fileMov).

    Generated from the following TL definition:
    ```tl
    storage.fileMov#4b09ebbc = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FileMp3(TLObject, TLRequest):
    """
    [Read `storage.fileMp3` docs](https://core.telegram.org/constructor/storage.fileMp3).

    Generated from the following TL definition:
    ```tl
    storage.fileMp3#528a0677 = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FileMp4(TLObject, TLRequest):
    """
    [Read `storage.fileMp4` docs](https://core.telegram.org/constructor/storage.fileMp4).

    Generated from the following TL definition:
    ```tl
    storage.fileMp4#b3cea0e4 = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FilePartial(TLObject, TLRequest):
    """
    [Read `storage.filePartial` docs](https://core.telegram.org/constructor/storage.filePartial).

    Generated from the following TL definition:
    ```tl
    storage.filePartial#40bc6f52 = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FilePdf(TLObject, TLRequest):
    """
    [Read `storage.filePdf` docs](https://core.telegram.org/constructor/storage.filePdf).

    Generated from the following TL definition:
    ```tl
    storage.filePdf#ae1e508d = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FilePng(TLObject, TLRequest):
    """
    [Read `storage.filePng` docs](https://core.telegram.org/constructor/storage.filePng).

    Generated from the following TL definition:
    ```tl
    storage.filePng#a4f63c0 = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FileUnknown(TLObject, TLRequest):
    """
    [Read `storage.fileUnknown` docs](https://core.telegram.org/constructor/storage.fileUnknown).

    Generated from the following TL definition:
    ```tl
    storage.fileUnknown#aa963b05 = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...

@final
class FileWebp(TLObject, TLRequest):
    """
    [Read `storage.fileWebp` docs](https://core.telegram.org/constructor/storage.fileWebp).

    Generated from the following TL definition:
    ```tl
    storage.fileWebp#1081464c = storage.FileType
    ```
    """
    def __new__(
        cls,
    ) -> Self: ...
    def to_dict(self) -> dict: ...
