# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class AuthKey:
    r"""
    Telegram's [Authorization Key](https://core.telegram.org/mtproto/auth_key).

    This library does not provide the means to generate a valid key,
    because doing so relies on (de-)serializing Telegram types.
    """
    @property
    def data(self) -> bytes:
        r"""
        完整的密钥数据 (256 字节)
        """
    def __new__(cls, data: builtins.bytes | builtins.str) -> AuthKey:
        r"""
        从 256 字节数据或创建 AuthKey

        Args:
            data: 256 字节的密钥数据

        Raises:
            ValueError: 如果数据长度不是 256 字节
        """
    @staticmethod
    def from_hex(hex_str: builtins.str) -> AuthKey:
        r"""
        从十六进制字符串创建 AuthKey

        Args:
            hex_str: 512 字符的十六进制字符串

        Returns:
            AuthKey 实例
        """
    def to_hex(self) -> builtins.str:
        r"""
        转换为十六进制字符串
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: AuthKey) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
